'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';

type Access='Open weights'|'Open code'|'Closed';
type Head='Discrete tokens'|'Direct regression'|'CVAE chunk'|'Diffusion'|'Flow matching'|'Video-action'|'Undisclosed';
type Model={name:string;org:string;year:number;access:Access;params:string;vision:string;language:string;fusion:string;head:Head;action:string;chunk:string;rate:string;metric:string;benchmark:string;url:string;data:string;note:string};

const models:Model[]=[
  {name:'ACT',org:'Stanford',year:2023,access:'Open code',params:'~80M class',vision:'Per-camera ResNet-18',language:'None',fusion:'Transformer encoder/decoder + CVAE latent',head:'CVAE chunk',action:'Joint-position sequence',chunk:'Typically 100 steps; temporal ensemble',rate:'50 Hz ALOHA control',metric:'80–90% on fine bimanual tasks',benchmark:'ALOHA real tasks · author reported',url:'https://tonyzhaozh.github.io/aloha/',data:'~10 min demonstrations per task in headline examples',note:'A strong task-specialist baseline. Chunking shortens the effective decision horizon, but the CVAE does not provide semantic planning.'},
  {name:'Diffusion Policy',org:'Columbia',year:2023,access:'Open code',params:'task-scale',vision:'ResNet-18 or point-cloud encoder',language:'None',fusion:'Observation-conditioned temporal model',head:'Diffusion',action:'Continuous action trajectory',chunk:'Prediction + receding execution horizons',rate:'Task/config dependent',metric:'+46.9% average over prior SOTA',benchmark:'12 tasks · 4 benchmarks · author reported',url:'https://diffusion-policy.cs.columbia.edu/',data:'Task-specific robot demonstrations',note:'Excellent multimodal continuous action modeling; iterative denoising adds latency and remains a reactive policy unless paired with a planner.'},
  {name:'RT-1',org:'Google Robotics',year:2022,access:'Closed',params:'35M',vision:'EfficientNet-B3 + FiLM + TokenLearner',language:'Universal Sentence Encoder conditioning',fusion:'Decoder-only Transformer',head:'Discrete tokens',action:'11 dimensions quantized into 256 bins',chunk:'One action per step',rate:'3 Hz',metric:'97% seen-task success; 76% novel task',benchmark:'700+ task real-robot suite · author reported',url:'https://robotics-transformer1.github.io/',data:'130K episodes · 700+ tasks · 13 robots',note:'The foundational token-policy recipe. Efficient, but low-rate autoregressive quantized control is a poor fit for very fine dexterity.'},
  {name:'RT-2-X',org:'Google DeepMind',year:2023,access:'Closed',params:'up to 55B',vision:'PaLI-X / PaLM-E visual stack',language:'Large VLM backbone',fusion:'Vision/language/action as one token sequence',head:'Discrete tokens',action:'Robot actions serialized as text tokens',chunk:'Autoregressive action tokens',rate:'Deployment dependent',metric:'3× emergent-skill generalization vs RT-2',benchmark:'RT-2 real suite · author reported',url:'https://robotics-transformer2.github.io/',data:'Web VLM data + Open X-Embodiment robot data',note:'Shows semantic transfer from internet pretraining, but action tokenization and model size make high-frequency control expensive.'},
  {name:'Octo 93M',org:'Berkeley · Stanford',year:2024,access:'Open weights',params:'93M',vision:'ViT patch encoders; flexible camera tokens',language:'T5 language encoder or goal image',fusion:'Block-wise Transformer with task/readout tokens',head:'Diffusion',action:'Dataset-specific continuous spaces',chunk:'Short continuous chunks',rate:'Hardware dependent',metric:'Adapted across 9 robot platforms',benchmark:'Cross-embodiment adaptation · native task metrics',url:'https://octo-models.github.io/',data:'800K Open X-Embodiment episodes',note:'A modular generalist initialization. New observations and action heads are first-class, but semantic capacity is far below multi-billion-parameter VLAs.'},
  {name:'OpenVLA 7B',org:'Stanford · Berkeley · TRI',year:2024,access:'Open weights',params:'7B',vision:'Fused DINOv2 + SigLIP',language:'Llama 2 7B via Prismatic',fusion:'Projected visual patches in the LLM token stream',head:'Discrete tokens',action:'7 dimensions, each quantized to token bins',chunk:'One action, autoregressive decode',rate:'~1–2 Hz unoptimized',metric:'+16.5 pp vs RT-2-X',benchmark:'29 tasks · multiple embodiments · author reported',url:'https://openvla.github.io/',data:'970K curated OXE robot episodes',note:'Very auditable and semantically capable; single-step discrete decoding is the main control bottleneck that later OFT replaces.'},
  {name:'OpenVLA-OFT',org:'Stanford',year:2025,access:'Open weights',params:'7B + small head',vision:'Fused DINOv2 + SigLIP',language:'Llama 2 7B',fusion:'Prismatic features + proprio projector',head:'Direct regression',action:'Parallel continuous 7-D actions · L1 objective',chunk:'8 steps on LIBERO',rate:'25–50× base OpenVLA inference',metric:'97.1% average success',benchmark:'LIBERO four-suite average',url:'https://openvla-oft.github.io/',data:'OpenVLA prior + target demonstrations',note:'A controlled demonstration that the same backbone becomes much stronger when the action interface changes.'},
  {name:'RDT-1B',org:'Tsinghua',year:2024,access:'Open weights',params:'1B action model',vision:'SigLIP',language:'T5-XXL encoder',fusion:'Alternating image/language cross-attention in DiT',head:'Diffusion',action:'Unified 128-D state/action interface',chunk:'64-step trajectory in canonical configs',rate:'Denoising dependent',metric:'State-of-the-art bimanual generalization claimed',benchmark:'ALOHA · SimplerEnv · RoboTwin native suites',url:'https://rdt-robotics.github.io/rdt-robotics/',data:'1M+ episodes from 46 datasets; 6K+ ALOHA adaptation',note:'Large action capacity and explicit heterogeneity handling; the enormous frozen T5 encoder raises memory cost without necessarily improving visuomotor precision.'},
  {name:'CogACT',org:'Microsoft Research',year:2024,access:'Open weights',params:'7B + up to 300M',vision:'DINOv2 + SigLIP',language:'Llama 2 7B / Prismatic',fusion:'Single cognition readout conditions action module',head:'Diffusion',action:'Continuous multi-step end-effector actions',chunk:'Multi-step + adaptive ensemble',rate:'Faster than autoregressive token decode',metric:'64.8% best DiT action-module average',benchmark:'SIMPLER ablation; +55% vs OpenVLA on real suite',url:'https://cogact.github.io/',data:'0.4M OXE trajectories + hundreds target demos',note:'Cleanly separates cognition from control and shows action-module scaling. One cognition token can also become an information bottleneck.'},
  {name:'π0',org:'Physical Intelligence',year:2024,access:'Open weights',params:'~3.3B',vision:'PaliGemma SigLIP vision tower',language:'Gemma 2B inside PaliGemma',fusion:'Two-expert transformer; attention shared across VLM/action streams',head:'Flow matching',action:'Continuous embodiment-specific vectors',chunk:'50 future actions',rate:'Up to 50 Hz robot control',metric:'68% average across dexterous evaluation',benchmark:'PI cross-embodiment task suite · author reported',url:'https://www.pi.website/blog/pi0',data:'10K+ hours multi-embodiment robot data',note:'The template most current VLAs copy: a pretrained VLM plus a smaller continuous action expert. Public weights do not include the full training corpus.'},
  {name:'SmolVLA 450M',org:'Hugging Face',year:2025,access:'Open weights',params:'450M',vision:'SigLIP in pruned SmolVLM2',language:'SmolLM2 decoder',fusion:'Interleaved self/cross attention; one state token',head:'Flow matching',action:'Continuous action chunks',chunk:'50 steps in released design',rate:'Async execution; device dependent',metric:'78.3% after community pretraining',benchmark:'SO-100 real suite; ~78% sync/async',url:'https://huggingface.co/blog/smolvla',data:'<30K public LeRobot episodes',note:'The efficiency reference: compact enough for local hardware, with asynchronous execution reducing pauses. Its semantic and cross-embodiment ceiling is lower.'},
  {name:'GR00T N1.7 3B',org:'NVIDIA',year:2026,access:'Open weights',params:'3B',vision:'Qwen3-VL / Cosmos-Reason2 vision stack',language:'Cosmos-Reason2-2B',fusion:'VLM features condition diffusion transformer',head:'Flow matching',action:'Up to 132-D; embodiment configs',chunk:'40 predicted; execution horizon configurable',rate:'35.9 Hz H100 TensorRT, one-camera test',metric:'92.80% randomized success',benchmark:'RoboTwin 2.0 as reported by LingBot VLA 2.0',url:'https://github.com/NVIDIA/Isaac-GR00T',data:'Real robot + EgoScale ego + simulation mixture',note:'Strong deployment engineering and whole-body latent actions. Benchmark variance of 5–6% and hardware/runtime mode must travel with every score.'},
  {name:'MolmoAct2 5B',org:'Ai2',year:2026,access:'Open weights',params:'5B',vision:'Molmo2-ER visual encoder',language:'Molmo2-ER autoregressive VLM',fusion:'Per-layer KV-cache bridge to action expert',head:'Flow matching',action:'Continuous chunks; optional open FAST tokenizer',chunk:'Checkpoint/embodiment specific',rate:'180 ms base call on H100',metric:'97.2% · 98.1% Think',benchmark:'LIBERO four-suite average',url:'https://allenai.org/blog/molmoact2',data:'Embodied reasoning + 720h+ YAM and named robot mixtures',note:'The strongest open disclosure package here: data, code, weights, rollouts and third-party real evaluation. Adaptive reasoning improves accuracy but raises call time to 790 ms.'},
  {name:'LingBot-VLA 2.0',org:'Robbyant · Ant Group',year:2026,access:'Open weights',params:'~4B class',vision:'Qwen3-VL vision + optional DINOv3 expert vision',language:'Qwen3-VL 4B class',fusion:'Paired VLM/action transformers with optional token MoE',head:'Flow matching',action:'Canonical 55-D whole-body action space',chunk:'25 deployed; up to 50 evaluation',rate:'~130 ms / call on RTX 4090D',metric:'92.8% randomized RoboTwin',benchmark:'RoboTwin 2.0; GM-100 and mobile tasks separate',url:'https://github.com/Robbyant/lingbot-vla-v2',data:'50K h robot + 10K h human ego across 20 embodiments',note:'Broad embodiment contract and unusually concrete deployment code. Aggregate private hours and cross-platform normalization remain hard to audit.'},
  {name:'LingBot-VA',org:'Robbyant · Ant Group',year:2026,access:'Open weights',params:'video-model class',vision:'Wan-style video latent encoder',language:'Text/video conditioning',fusion:'Dual-stream mixture-of-transformers with shared context',head:'Video-action',action:'Action diffusion interleaved with future video generation',chunk:'Video/action denoising horizons',rate:'Asynchronous execution + KV cache',metric:'Long-horizon gains on LIBERO-LONG',benchmark:'LIBERO-LONG · RoboTwin 2.0',url:'https://github.com/Robbyant/lingbot-va',data:'Robot video-action trajectories + post-training suites',note:'World prediction and action are trained together, a promising memory substrate. Open issues document code/paper discrepancies in denoising steps and MoT implementation.'},
  {name:'Gemini Robotics',org:'Google DeepMind',year:2025,access:'Closed',params:'Undisclosed',vision:'Gemini multimodal encoder',language:'Gemini backbone',fusion:'VLA policy plus separate embodied-reasoning model',head:'Undisclosed',action:'Continuous robot commands; embodiment adapters',chunk:'Undisclosed',rate:'Undisclosed',metric:'2× performance on generalization benchmark claimed',benchmark:'Private multi-embodiment suite',url:'https://deepmind.google/discover/blog/gemini-robotics-brings-ai-into-the-physical-world/',data:'Private cross-embodiment robot data + Gemini pretraining',note:'High semantic/reasoning capacity, but encoder/action-head details, parameters, data and reproducible control metrics are not public.'},
  {name:'Figure Helix 02',org:'Figure AI',year:2026,access:'Closed',params:'Undisclosed',vision:'Multi-camera visual encoder',language:'S2 semantic VLM',fusion:'S2 slow reasoning → S1 fast visuomotor → S0 whole-body control',head:'Undisclosed',action:'Upper-body + locomotion whole-body commands',chunk:'Multi-rate hierarchy',rate:'S1 reported at 200 Hz class in Helix family',metric:'4 min · 61 kitchen actions · no reset',benchmark:'Publisher demonstration, not a benchmark',url:'https://www.figure.ai/news/helix-02',data:'Private human/robot fleet data',note:'The clearest commercial hierarchy, but almost every architectural dimension required for reproduction is undisclosed.'},
];

const headNotes:Record<Head,[string,string,string]>={
  'Discrete tokens':['Quantize each action dimension, then decode autoregressively.','Semantic reuse; simple VLM fine-tuning.','Slow; quantization error; weak high-rate dexterity.'],
  'Direct regression':['Predict the whole continuous chunk in parallel.','Fast and stable when one mode dominates.','Averages incompatible modes; less expressive uncertainty.'],
  'CVAE chunk':['Latent-conditioned transformer emits a future trajectory.','Smooth chunks; effective with small task datasets.','Posterior collapse and limited semantic breadth.'],
  'Diffusion':['Iteratively denoise a multimodal action trajectory.','Expressive continuous multi-modal control.','Several network evaluations per action call.'],
  'Flow matching':['Learn a velocity field from noise to an action chunk.','Fewer integration steps; current VLA default.','Still iterative; normalization and horizon are critical.'],
  'Video-action':['Generate future visual state and action in a coupled model.','Potential dynamics, planning and action in one substrate.','Very expensive; pixels can be plausible while contact is wrong.'],
  'Undisclosed':['Publisher has not released an implementable action-decoder contract.','Commercial evidence can still reveal system-level capability.','No reproducibility, latency attribution or architectural ablation.'],
};

type Domain='Simulation'|'Real robot';
type BoardRow={benchmark:string;domain:Domain;model:string;score:number;display:string;metric:string;setting:string;access:Access;date:string;url:string;caveat:string};
const boardRows:BoardRow[]=[
  {benchmark:'RoboCasa365',domain:'Simulation',model:'Xiaomi-Robotics-1',score:57.4,display:'57.4',metric:'Overall success %',setting:'50-task multitask · three splits',access:'Open weights',date:'2026-08-21',url:'https://robocasa.ai/leaderboard.html',caveat:'Official verified leaderboard.'},
  {benchmark:'RoboCasa365',domain:'Simulation',model:'ABot-M0.6',score:46.6,display:'46.6',metric:'Overall success %',setting:'50-task multitask · three splits',access:'Closed',date:'2026-08-21',url:'https://robocasa.ai/leaderboard.html',caveat:'Official board; checkpoint privately verifiable by maintainers.'},
  {benchmark:'RoboCasa365',domain:'Simulation',model:'ABot-M0.5',score:40.3,display:'40.3',metric:'Overall success %',setting:'50-task multitask · three splits',access:'Closed',date:'2026-08-21',url:'https://robocasa.ai/leaderboard.html',caveat:'Official board.'},
  {benchmark:'RoboCasa365',domain:'Simulation',model:'PRTS',score:39.6,display:'39.6',metric:'Overall success %',setting:'50-task multitask · three splits',access:'Open weights',date:'2026-08-21',url:'https://robocasa.ai/leaderboard.html',caveat:'Official verified leaderboard.'},
  {benchmark:'RoboTwin 2.0',domain:'Simulation',model:'LingBot-VLA 2.0',score:93.16,display:'93.16',metric:'Mean clean/random success %',setting:'50 tasks · ALOHA-AgileX',access:'Open weights',date:'2026-07-31',url:'https://github.com/Robbyant/lingbot-vla-v2',caveat:'Mean of publisher-reported 93.52 clean and 92.80 randomized.'},
  {benchmark:'RoboTwin 2.0',domain:'Simulation',model:'LingBot-VLA 1.0',score:87.62,display:'87.62',metric:'Mean clean/random success %',setting:'50 tasks · ALOHA-AgileX',access:'Open weights',date:'2026-07-31',url:'https://github.com/Robbyant/lingbot-vla-v2',caveat:'Mean of 88.56 clean and 86.68 randomized.'},
  {benchmark:'RoboTwin 2.0',domain:'Simulation',model:'π0.5',score:79.75,display:'79.75',metric:'Mean clean/random success %',setting:'50 tasks · ALOHA-AgileX',access:'Open weights',date:'2026-07-31',url:'https://github.com/Robbyant/lingbot-vla-v2',caveat:'Mean of 82.74 clean and 76.76 randomized.'},
  {benchmark:'LIBERO',domain:'Simulation',model:'MolmoAct2-Think',score:98.1,display:'98.1',metric:'Four-suite avg success %',setting:'Post-trained · four standard suites',access:'Open weights',date:'2026-05-31',url:'https://allenai.org/blog/molmoact2',caveat:'Publisher result; adaptive-depth reasoning.'},
  {benchmark:'LIBERO',domain:'Simulation',model:'MolmoAct2',score:97.2,display:'97.2',metric:'Four-suite avg success %',setting:'Post-trained · four standard suites',access:'Open weights',date:'2026-05-31',url:'https://allenai.org/blog/molmoact2',caveat:'Publisher result.'},
  {benchmark:'LIBERO',domain:'Simulation',model:'OpenVLA-OFT',score:97.1,display:'97.1',metric:'Four-suite avg success %',setting:'Post-trained · four standard suites',access:'Open weights',date:'2025-02-28',url:'https://openvla-oft.github.io/',caveat:'Publisher result; evaluation stack can move scores.'},
  {benchmark:'GM-100 / Cobot Magic',domain:'Real robot',model:'LingBot-VLA 2.0',score:34.4,display:'34.4',metric:'Success rate %',setting:'AgileX Cobot Magic · progress 66.2',access:'Open weights',date:'2026-07-31',url:'https://github.com/Robbyant/lingbot-vla-v2',caveat:'Publisher-run real benchmark.'},
  {benchmark:'GM-100 / Cobot Magic',domain:'Real robot',model:'π0.5',score:32.2,display:'32.2',metric:'Success rate %',setting:'AgileX Cobot Magic · progress 59.1',access:'Open weights',date:'2026-07-31',url:'https://github.com/Robbyant/lingbot-vla-v2',caveat:'Publisher reproduction.'},
  {benchmark:'GM-100 / Cobot Magic',domain:'Real robot',model:'GR00T N1.7',score:17.8,display:'17.8',metric:'Success rate %',setting:'AgileX Cobot Magic · progress 36.3',access:'Open weights',date:'2026-07-31',url:'https://github.com/Robbyant/lingbot-vla-v2',caveat:'Publisher reproduction.'},
  {benchmark:'Cortex / Ai2 bimanual',domain:'Real robot',model:'MolmoAct2',score:.51,display:'0.51',metric:'Graded task score',setting:'8 bimanual tasks · third-party evaluation',access:'Open weights',date:'2026-05-31',url:'https://allenai.org/blog/molmoact2',caveat:'Not binary success; independent evaluator retained by Ai2.'},
  {benchmark:'Cortex / Ai2 bimanual',domain:'Real robot',model:'OpenVLA-OFT',score:.36,display:'0.36',metric:'Graded task score',setting:'8 bimanual tasks · third-party evaluation',access:'Open weights',date:'2026-05-31',url:'https://allenai.org/blog/molmoact2',caveat:'Same evaluator and task suite.'},
  {benchmark:'Cortex / Ai2 bimanual',domain:'Real robot',model:'π0.5',score:.32,display:'0.32',metric:'Graded task score',setting:'8 bimanual tasks · third-party evaluation',access:'Open weights',date:'2026-05-31',url:'https://allenai.org/blog/molmoact2',caveat:'Same evaluator and task suite.'},
];

const benchmarks=[
  {name:'RoboCasa365',domain:'SIM',tasks:'365 total · public board evaluates 50',embodiment:'Mobile Franka in 2,500+ kitchens',metric:'Atomic-seen · composite-seen · composite-unseen success',status:'VERIFIED BOARD',url:'https://robocasa.ai/leaderboard.html'},
  {name:'RoboTwin 2.0',domain:'SIM',tasks:'50 bimanual tasks · 100 trials/task',embodiment:'ALOHA-AgileX board · 5 supported robots',metric:'Clean2clean · clean2random · mean',status:'VERIFIED BOARD',url:'https://robotwin-platform.github.io/leaderboard'},
  {name:'LIBERO',domain:'SIM',tasks:'130 language-conditioned tasks',embodiment:'Franka · robosuite/MuJoCo',metric:'Binary success across Spatial/Object/Goal/Long suites',status:'MAINTAINER TABLES',url:'https://libero-project.github.io/'},
  {name:'SIMPLER',domain:'SIM ↔ REAL',tasks:'Google Robot + WidowX real-matched tasks',embodiment:'Real-to-sim visual/control matching',metric:'Sim success and correlation with real policy rankings',status:'PROTOCOL',url:'https://simpler-env.github.io/'},
  {name:'VLABench',domain:'SIM',tasks:'100 categories · 2,000+ objects',embodiment:'Language-conditioned tabletop policy/workflow',metric:'Progress + success; separate non-interactive reasoning score',status:'BOARD COMING SOON',url:'https://vlabench.github.io/'},
  {name:'CALVIN',domain:'SIM',tasks:'34 skills · 1,000 fixed five-step chains',embodiment:'Franka tabletop · ABC-D environments',metric:'% completing 1…5 steps + mean chain length',status:'HOSTED BOARD',url:'https://calvin.cs.uni-freiburg.de/'},
  {name:'RLBench',domain:'SIM',tasks:'100 manipulation tasks',embodiment:'Franka in CoppeliaSim',metric:'Per-task success under few-shot demonstrations',status:'PUBLIC PROTOCOL',url:'https://sites.google.com/view/rlbench'},
  {name:'ManiSkill',domain:'SIM',tasks:'Rigid, articulated and mobile manipulation suites',embodiment:'Multiple robots · SAPIEN',metric:'Task success with standardized evaluation episodes',status:'PUBLIC CHALLENGES',url:'https://maniskill.ai/'},
  {name:'BEHAVIOR-1K',domain:'SIM',tasks:'1,000 activities · 2026 board uses 100',embodiment:'Onboard RGB-D + proprio · supported robots',metric:'Fraction of BDDL goal predicates + efficiency tie-breaks',status:'LIVE CHALLENGE',url:'https://behavior.stanford.edu/challenge/'},
  {name:'RoboEval',domain:'SIM',tasks:'10 bimanual bases + pose/semantic variants',embodiment:'Bimanual YAM-style manipulation',metric:'Graded success + path, collision, slip and jerk diagnostics',status:'HOSTED BOARD',url:'https://robo-eval.github.io/'},
  {name:'GM-100',domain:'REAL',tasks:'100+ detail-oriented real manipulation tasks',embodiment:'Cobot Magic · Dobot Xtrainer preview',metric:'Progress score + binary success',status:'PREVIEW BOARD',url:'https://www.rhos.ai/research/gm-100/results/'},
  {name:'RoboArena',domain:'REAL',tasks:'Open evaluator-chosen task distribution',embodiment:'Franka / DROID platform',metric:'Double-blind pairwise arena rating',status:'LIVE REAL BOARD',url:'https://robo-arena.github.io/'},
  {name:'SO-100 / SO-101',domain:'REAL',tasks:'Pick-place · stack · sort suites',embodiment:'Affordable LeRobot arms',metric:'Task success, completion time and throughput',status:'RECIPE-LEVEL',url:'https://huggingface.co/blog/smolvla'},
  {name:'ALOHA',domain:'REAL',tasks:'Fine bimanual task suites',embodiment:'Static or mobile ALOHA',metric:'Binary success, often 10–50 trials/task',status:'PAPER-SPECIFIC',url:'https://tonyzhaozh.github.io/aloha/'},
];

const native=[
  {name:'OpenVLA',kind:'architecture',src:'https://openvla.github.io/static/images/openvla_model.jpg',url:'https://openvla.github.io/'},
  {name:'CogACT',kind:'architecture',src:'https://cogact.github.io/static/images/model.png',url:'https://cogact.github.io/'},
  {name:'Octo',kind:'architecture',src:'https://octo-models.github.io/architecture.jpg',url:'https://octo-models.github.io/'},
  {name:'OpenVLA-OFT',kind:'benchmark',src:'https://openvla-oft.github.io/static/images/libero_task_performance_results.png',url:'https://openvla-oft.github.io/'},
];

const transferSystems=[
  {name:'RT-2',mode:'Zero-shot semantic transfer',prompt:'Language instruction',update:'None at test time',train:'Internet vision-language + robot trajectories',evidence:'Held-out objects, commands and semantic reasoning; 6k evaluation trials overall.',axis:'Object · instruction · semantics',url:'https://robotics-transformer2.github.io/'},
  {name:'ICRT',mode:'In-context imitation',prompt:'1+ robot sensorimotor trajectories',update:'None on prompt task',train:'DROID pretraining + 1,098-trajectory multi-task set',evidence:'Unseen pick-place/poking tasks and objects; 16-action continuous chunks.',axis:'Task · object · environment',url:'https://icrt.dev/'},
  {name:'Instant Policy',mode:'In-context imitation',prompt:'1–2 robot or mapped human demonstrations',update:'None at deployment',train:'Simulated pseudo-demonstration meta-training',evidence:'Real closed-loop tasks, perturbations, object geometry and cross-embodiment transfer.',axis:'Task · geometry · embodiment',url:'https://www.robot-learning.uk/instant-policy'},
  {name:'RICL-π₀-FAST',mode:'Retrieval-augmented ICL',prompt:'10–20 retrieved robot demonstrations',update:'None for ICL; optional finetune separately',train:'ICL recipe injected into pretrained VLA',evidence:'Novel objects, motions and scenes; ICL and finetune results reported separately.',axis:'Task · object · motion · scene',url:'https://ricl-vla.github.io/'},
  {name:'MimicDroid',mode:'Human-video ICL',prompt:'Few human play videos',update:'None on prompted task',train:'Retrieved context-target pairs from human play video',evidence:'Humanoid sim benchmark + real G1 rollouts; three novelty levels.',axis:'Object · scene · humanoid task',url:'https://ut-austin-rpl.github.io/MimicDroid/index.html'},
];

export default function ModelArchitecturesPage(){
  const [access,setAccess]=useState<'All'|Access>('All');
  const [head,setHead]=useState<'All'|Head>('All');
  const [query,setQuery]=useState('');
  const [active,setActive]=useState(models[5]);
  const [board,setBoard]=useState('RoboCasa365');
  const [boardDomain,setBoardDomain]=useState<'All'|Domain>('All');
  const [boardAccess,setBoardAccess]=useState<'All'|Access>('All');
  const [boardQuery,setBoardQuery]=useState('');
  const [boardSort,setBoardSort]=useState<'score'|'model'|'date'>('score');
  const [boardDesc,setBoardDesc]=useState(true);
  const visible=useMemo(()=>models.filter(m=>(access==='All'||m.access===access)&&(head==='All'||m.head===head)&&(!query||Object.values(m).join(' ').toLowerCase().includes(query.toLowerCase()))),[access,head,query]);
  const boardNames=[...new Set(boardRows.map(r=>r.benchmark))];
  const ranked=useMemo(()=>boardRows.filter(r=>(board==='All'||r.benchmark===board)&&(boardDomain==='All'||r.domain===boardDomain)&&(boardAccess==='All'||r.access===boardAccess)&&(!boardQuery||Object.values(r).join(' ').toLowerCase().includes(boardQuery.toLowerCase()))).sort((a,b)=>{const av=boardSort==='score'?a.score:a[boardSort];const bv=boardSort==='score'?b.score:b[boardSort];const d=typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv));return boardDesc?-d:d}),[board,boardDomain,boardAccess,boardQuery,boardSort,boardDesc]);
  return <main className="arch-page">
    <header className="training-topbar"><Link className="brand" href="/"><span>EØ</span>EGØ INDEX</Link><nav><Link href="/robotics-2026">Guide</Link><Link href="/real2sim">Real2Sim</Link><Link href="/model-architectures" aria-current="page">Architectures</Link><Link href="/training-strategies">Training</Link><Link href="/#matrix">Topology</Link></nav><Link className="edition" href="/">Owner audit · 31 Aug 2026</Link></header>
    <section className="arch-hero"><p className="eyebrow">PIXELS → TOKENS → TRAJECTORIES</p><h1>INSIDE THE<br/><em>ROBOT POLICY.</em></h1><p>The encoder decides what can be seen. The backbone decides what can be related. The action head decides what can be controlled—and at what latency, precision and horizon.</p><div className="arch-hero-flow"><span>RGB · DEPTH<br/><b>OBSERVATION</b></span><i>→</i><span>ViT · SigLIP · DINO<br/><b>ENCODER</b></span><i>→</i><span>LLM · TRANSFORMER<br/><b>BACKBONE</b></span><i>→</i><span>DiT · FLOW · TOKENS<br/><b>ACTION HEAD</b></span><i>→</i><span>JOINT · EE · LATENT<br/><b>ROBOT</b></span></div></section>

    <section className="arch-primer"><div><p className="eyebrow">OWNER RULE 01</p><h2>“VLA” DOES NOT<br/>SPECIFY THE POLICY.</h2></div><div>{[['ENCODER','Spatial precision, viewpoint robustness and temporal context enter here.'],['BACKBONE','Capacity may buy semantics, but only if robot signals are fused without destroying control detail.'],['ACTION HEAD','Discrete, regression, diffusion and flow heads impose different latency and multimodality.'],['EXECUTION','Prediction horizon is not execution horizon; receding control can replan before a chunk finishes.']].map((x,i)=><article key={x[0]}><b>0{i+1}</b><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>

    <section className="arch-workbench"><div className="section-heading"><div><p className="eyebrow">01 / ARCHITECTURE WORKBENCH</p><h2>TRACE THE SIGNAL<br/>END TO END.</h2></div><p className="section-note">“Undisclosed” is shown explicitly. Parameter counts exclude external encoders where publishers report them separately.</p></div><div className="arch-filters"><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search encoder, backbone, head, action…"/></label><div><b>ACCESS</b>{(['All','Open weights','Open code','Closed'] as const).map(v=><button key={v} className={access===v?'active':''} onClick={()=>setAccess(v)}>{v}</button>)}</div><div><b>ACTION HEAD</b>{(['All','Discrete tokens','Direct regression','CVAE chunk','Diffusion','Flow matching','Video-action','Undisclosed'] as const).map(v=><button key={v} className={head===v?'active':''} onClick={()=>setHead(v)}>{v}</button>)}</div></div>
      <div className="arch-table-head"><span>Model / scale</span><span>Vision + language</span><span>Policy backbone</span><span>Action head</span><span>Native evidence</span></div>{visible.map(m=><button className={'arch-row '+(active.name===m.name?'active':'')} key={m.name} onClick={()=>setActive(m)}><span><strong>{m.name}</strong><small>{m.org} · {m.year}</small><i>{m.params} · {m.access}</i></span><span><b>{m.vision}</b><p>{m.language}</p></span><span><b>{m.fusion}</b><p>{m.data}</p></span><span><b>{m.head}</b><p>{m.action}</p><small>{m.chunk}</small></span><span><b>{m.metric}</b><p>{m.benchmark}</p></span></button>)}</section>

    <section className="arch-inspector"><header><div><p>{active.access} · {active.params}</p><h2>{active.name}</h2></div><a href={active.url} target="_blank" rel="noreferrer">Primary source ↗</a></header><div className="arch-pipeline"><article><span>01 / ENCODE</span><h3>{active.vision}</h3><p>{active.language}</p></article><i>→</i><article><span>02 / FUSE + REASON</span><h3>{active.fusion}</h3><p>{active.data}</p></article><i>→</i><article className="hot"><span>03 / DECODE ACTION</span><h3>{active.head}</h3><p>{active.action}</p></article><i>→</i><article><span>04 / EXECUTE</span><h3>{active.chunk}</h3><p>{active.rate}</p></article></div><footer><b>ARCHITECTURE VERDICT</b><span>{active.note}</span></footer></section>

    <section className="arch-heads"><div className="section-heading"><div><p className="eyebrow">02 / ACTION-HEAD TAXONOMY</p><h2>THE LAST LAYER<br/>CHANGES THE ROBOT.</h2></div></div><div>{(Object.entries(headNotes) as [Head,[string,string,string]][]).map(([name,note])=><button key={name} className={head===name?'active':''} onClick={()=>setHead(name)}><span>{models.filter(m=>m.head===name).length} indexed</span><h3>{name}</h3><p>{note[0]}</p><dl><dt>BUYS</dt><dd>{note[1]}</dd><dt>COSTS</dt><dd>{note[2]}</dd></dl></button>)}</div></section>

    <section className="arch-bench"><div className="section-heading"><div><p className="eyebrow">03 / COMPARABLE SLICE</p><h2>SAME BENCHMARK.<br/>THEN COMPARE.</h2></div><p className="section-note">LIBERO four-suite averages after task post-training. Even here, recipes, seeds and evaluation stacks differ.</p></div><div className="libero-chart">{[['MolmoAct2-Think',98.1,'#ff6337'],['MolmoAct2',97.2,'#1744e8'],['OpenVLA-OFT',97.1,'#c8ff36']].map(x=><div key={String(x[0])}><span>{x[0]}</span><i><b style={{width:`${Number(x[1])-90}%`,background:String(x[2])}}/></i><strong>{x[1]}%</strong></div>)}<small>axis truncated: 90–100% · publisher-reported averages</small></div><div className="arch-noncompare"><header><b>DO NOT PUT THESE ON THE SAME BAR CHART</b><span>Useful evidence, incompatible denominators</span></header>{[['MolmoAct2','87.1%','15-trial/task Franka zero-shot average'],['LingBot-VLA 2.0','60.0%','Fridge sorting in-domain long-horizon SR'],['GR00T N1.7','35.9 Hz','H100 TensorRT, one camera, 4 denoising steps'],['SmolVLA','9.7 s','Async average completion vs 13.75 s sync'],['Video2Sim2Real','95.7%','Seven dexterous tasks, 10 trials each'],['Figure Helix 02','4 min','61-action demo, no benchmark or reset']].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><p>{x[2]}</p></article>)}</div></section>

    <section className="policy-board"><div className="section-heading"><div><p className="eyebrow">04 / QUERYABLE LEADERBOARD</p><h2>SORT WITHIN<br/>ONE PROTOCOL.</h2></div><p className="section-note">Default view keeps one benchmark selected. Choose “All” only to search the evidence ledger—mixed scores are not a global ranking.</p></div><div className="board-controls"><label><span>⌕</span><input value={boardQuery} onChange={e=>setBoardQuery(e.target.value)} placeholder="Search model, setting, caveat…"/></label><select value={board} onChange={e=>setBoard(e.target.value)}><option value="All">All evidence — do not rank</option>{boardNames.map(b=><option key={b}>{b}</option>)}</select><select value={boardDomain} onChange={e=>setBoardDomain(e.target.value as 'All'|Domain)}><option>All</option><option>Simulation</option><option>Real robot</option></select><select value={boardAccess} onChange={e=>setBoardAccess(e.target.value as 'All'|Access)}><option>All</option><option>Open weights</option><option>Open code</option><option>Closed</option></select><select value={boardSort} onChange={e=>setBoardSort(e.target.value as 'score'|'model'|'date')}><option value="score">Sort: score</option><option value="model">Sort: model</option><option value="date">Sort: date</option></select><button onClick={()=>setBoardDesc(v=>!v)}>{boardDesc?'Descending ↓':'Ascending ↑'}</button></div><div className="board-head"><span>Rank</span><span>Model / access</span><span>Score</span><span>Protocol</span><span>Evidence note</span></div>{ranked.map((r,i)=><a className="board-row" key={`${r.benchmark}-${r.model}`} href={r.url} target="_blank" rel="noreferrer"><span>{String(i+1).padStart(2,'0')}</span><span><b>{r.model}</b><small>{r.benchmark} · {r.domain} · {r.access}</small></span><span><strong>{r.display}</strong><small>{r.metric}</small></span><span><b>{r.setting}</b><small>{r.date}</small></span><span>{r.caveat} ↗</span></a>)}</section>

    <section className="benchmark-atlas"><div className="section-heading"><div><p className="eyebrow">05 / COMMON BENCHMARK ATLAS</p><h2>WHAT THE FIELD<br/>ACTUALLY USES.</h2></div><p className="section-note">A “public benchmark” may offer an official verified board, only a reproducible protocol, or merely paper-specific tables. Those are different governance levels.</p></div><div>{benchmarks.map(b=><a key={b.name} href={b.url} target="_blank" rel="noreferrer"><header><span>{b.domain}</span><i>{b.status}</i></header><h3>{b.name}</h3><p>{b.tasks}</p><dl><dt>EMBODIMENT</dt><dd>{b.embodiment}</dd><dt>METRIC</dt><dd>{b.metric}</dd></dl></a>)}</div></section>

    <section className="arch-native"><div className="section-heading"><div><p className="eyebrow">06 / NATIVE VISUALS</p><h2>READ THEIR<br/>ACTUAL DIAGRAMS.</h2></div><p className="section-note">Official publisher figures; click through for surrounding methodology and caveats.</p></div><div>{native.map(n=><a key={n.name} href={n.url} target="_blank" rel="noreferrer"><div><img src={n.src} alt={`${n.name} official ${n.kind} figure`}/></div><span><b>{n.name}</b><i>{n.kind} · official source ↗</i></span></a>)}</div></section>

    <section className="transfer-regimes" id="transfer-regimes"><div className="section-heading"><div><p className="eyebrow">07 / TRANSFER REGIMES</p><h2>“ZERO-SHOT” IS<br/>NOT ONE THING.</h2></div><p className="section-note">State what is unseen, what enters the context, and whether any parameter, memory or retrieval index changes. Otherwise the label is not auditable.</p></div>
      <div className="transfer-spectrum">{[
        ['CLOSED-SET','Seen task distribution','No novelty claim; useful for reliability and regression.'],
        ['ZERO-SHOT','No target examples or update','Must name held-out axis: instruction, object, scene, task, embodiment or dynamics.'],
        ['IN-CONTEXT','Examples in the prompt','Frozen parameters; demonstration trajectories or video alter behavior through context.'],
        ['FEW-SHOT UPDATE','A small target set changes weights','Adaptation, not ICL. Report examples, optimizer steps and target-test separation.'],
        ['ONLINE LEARNING','Deployment experience changes policy','Requires safety, replay, versioning and a moving evaluation boundary.'],
      ].map((x,i)=><article key={x[0]}><span>0{i+1}</span><b>{x[0]}</b><strong>{x[1]}</strong><p>{x[2]}</p></article>)}</div>
      <div className="transfer-contrast"><article><span>ZERO-SHOT CONTRACT</span><h3>WHAT WAS ABSENT?</h3><ul><li>Target task demonstrations</li><li>Target object category or instance</li><li>Target scene / viewpoint</li><li>Target embodiment or action space</li><li>Target language formulation</li><li>Test-time retrieval, search or gradient update</li></ul></article><article><span>ICL CONTRACT</span><h3>WHAT ENTERED CONTEXT?</h3><ul><li>Robot trajectory, human video, goal image or language</li><li>Number and selection of examples</li><li>Context length and temporal compression</li><li>Manual vs learned retrieval</li><li>Whether parameters truly stayed frozen</li><li>Latency and behavior with a wrong prompt</li></ul></article><aside><b>OWNER RULE</b><p>A model may be zero-shot on objects, in-context on task intent, and fully in-domain on embodiment—all in the same trial.</p><strong>Report the vector, not the adjective.</strong></aside></div>
      <div className="transfer-table"><header><span>System / regime</span><span>Test-time prompt</span><span>Parameter update</span><span>Training substrate</span><span>Claimed evaluation axis</span></header>{transferSystems.map(s=><a key={s.name} href={s.url} target="_blank" rel="noreferrer"><span><b>{s.name}</b><small>{s.mode}</small></span><span>{s.prompt}</span><span>{s.update}</span><span>{s.train}</span><span><b>{s.axis}</b><small>{s.evidence} ↗</small></span></a>)}</div>
      <div className="transfer-tests"><header><b>MINIMUM ABLATIONS</b><span>Evidence that context—not leakage or task recognition alone—changes the policy</span></header>{[['NO CONTEXT','Base policy on the identical held-out trials.'],['CORRECT CONTEXT','Prompt examples for the intended task.'],['WRONG CONTEXT','Plausible but mismatched examples; behavior should change predictably.'],['SHUFFLED / PARTIAL','Break order, remove action/state or hide key phases.'],['NOVELTY LADDER','Seen → unseen object → unseen scene → unseen task/embodiment.'],['ICL VS UPDATE','Equal demo budget, wall time and evaluation trials.']].map(x=><article key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div>
    </section>

    <section className="arch-rules"><div><p className="eyebrow">08 / READING GUIDE</p><h2>WHAT ACTUALLY<br/>MOVES THE FRONTIER.</h2></div><ol><li><b>Spatial features</b><span>Semantic VLM encoders can recognize the mug yet miss millimeter geometry. Fused DINO/depth/3D tokens are attempts to preserve both.</span></li><li><b>Continuous chunks</b><span>The field is converging on continuous multi-step heads because single-action token decoding is slow and brittle for dexterity.</span></li><li><b>Closed-loop cadence</b><span>A 50-step prediction is not 50 open-loop steps. Good systems execute a prefix, observe again, reconcile overlap and recover.</span></li><li><b>Hierarchy + memory</b><span>Bigger action heads do not create agency. Long workflows still need task state, planning, verification and recovery above the motor policy.</span></li><li><b>Data contract</b><span>Every action head is married to normalization, coordinate frames, control mode and embodiment. Architecture portability does not imply checkpoint portability.</span></li></ol></section>
  </main>;
}
