const collection = 'comparison_tables_2011_2026';
const collectionTitle = 'Comparison-table additions · 2011–2026';

type Core = {
  name: string;
  url: string;
  venue: string;
  kinds: string[];
  release: string;
  access: string;
  accessGroup: string;
  scale: string;
  input: string;
  output: string;
};

function entry(core: Core, details: Record<string, unknown> = {}) {
  return {
    id: `${collection}::${core.name}`,
    collection,
    collectionTitle,
    signals: [],
    tasks: ['General'],
    scenes: [],
    sceneCoverage: '',
    sequenceDuration: null,
    camera: '',
    cameraGroup: null,
    cameraView: null,
    captureDevices: [],
    robotInterfaces: [],
    companies: [],
    dataFormats: [],
    capabilities: [],
    dataProvenance: [],
    referenceTags: [],
    renderMethods: [],
    geometryLayers: [],
    systemLayers: [],
    libraryCategory: 'Method / paper',
    agenticWorkflows: [],
    agenticModules: [],
    agenticLayers: [],
    feedbackSignals: [],
    agenticDesign: '',
    computeCost: '',
    limitations: '',
    components: [],
    componentFamilies: [],
    inputGroups: [],
    outputGroups: [],
    benchmarks: [],
    comparisonMetrics: [],
    evaluations: [],
    featured: false,
    impact: null,
    snapshot: null,
    ...core,
    ...details,
  };
}

export const tableAdditions = [
  entry({
    name: 'EPFL-Smart-Kitchen-30',
    url: 'https://amathislab.github.io/EPFL-Smart-Kitchen/',
    venue: 'NeurIPS 2025 · Datasets and Benchmarks',
    kinds: ['Dataset'],
    release: '2025',
    access: 'Open Zenodo release',
    accessGroup: 'Open',
    scale: '29.7 h; mean recording 35.9 min; 16 participants; 60,189 dense action segments',
    input: 'synchronized egocentric and exocentric RGB-D, audio, IMU, gaze, and language',
    output: 'global 3D body/hand pose, dense action segments, and calibrated multiview recordings',
  }, {
    signals: ['RGB', '3D / pose', 'Gaze', 'IMU', 'Ego–exo', 'Language'],
    tasks: ['Manipulation', 'Human motion', 'Perception'],
    scenes: ['Indoor', 'Kitchen / household'],
    sceneCoverage: 'Four recipes in an instrumented kitchen',
    sequenceDuration: {unit: 'recording', average: '35.9 min', distribution: '29.7 h across 16 participants', basis: 'Reported'},
    camera: 'nine static cameras plus a HoloLens egocentric RGB-D view',
    cameraGroup: 'Calibration / intrinsics',
    cameraView: 'Multi-camera / multiview',
    captureDevices: ['HoloLens'],
    capabilities: ['Understanding / recognition', 'Tracking / localization', 'Data capture / annotation'],
    dataProvenance: ['Real capture'],
    inputGroups: ['RGB / video', 'Depth / RGB-D', 'Multiview', 'Language', 'Audio', 'Gaze', 'IMU', 'Hand / body pose', 'Human demonstration'],
    outputGroups: ['Dataset / labels', 'Hand / body motion', 'Camera / trajectory'],
  }),
  entry({
    name: 'EgoPER',
    url: 'https://openaccess.thecvf.com/content/CVPR2024/html/Lee_Error_Detection_in_Egocentric_Procedural_Task_Videos_CVPR_2024_paper.html',
    venue: 'CVPR 2024',
    kinds: ['Dataset'],
    release: '2024',
    access: 'Available by author request',
    accessGroup: 'Gated / request',
    scale: '386 source videos (213 normal, 173 erroneous); 28 h; five cooking procedures',
    input: 'untrimmed egocentric RGB-D procedural videos with audio, gaze, and hand tracking',
    output: 'frame-wise steps, errors, bounding boxes, audio, gaze, and hand tracks',
  }, {
    signals: ['RGB', '3D / pose', 'Gaze'],
    tasks: ['Manipulation', 'Perception', 'Assistance'],
    scenes: ['Indoor', 'Kitchen / household'],
    sceneCoverage: 'Five cooking procedures',
    sequenceDuration: {unit: 'video', distribution: 'task-level mean video length 1.6–8.4 min', basis: 'Reported'},
    camera: 'egocentric RGB-D',
    cameraView: 'Monocular',
    capabilities: ['Understanding / recognition', 'Tracking / localization', 'Data capture / annotation'],
    dataProvenance: ['Real capture'],
    inputGroups: ['RGB / video', 'Depth / RGB-D', 'Audio', 'Gaze', 'Hand / body pose', 'Human demonstration'],
    outputGroups: ['Dataset / labels', 'Perception / tracking', 'Benchmark / evaluation'],
  }),
  entry({
    name: 'PVSG',
    url: 'https://openaccess.thecvf.com/content/CVPR2023/html/Yang_Panoptic_Video_Scene_Graph_Generation_CVPR_2023_paper.html',
    venue: 'CVPR 2023',
    kinds: ['Dataset'],
    release: '2023',
    access: 'Open dataset and code',
    accessGroup: 'Open',
    scale: '400 videos; approximately 8.5 h; mean 76.5 s; 111 ego and 289 exo videos',
    input: 'mixed egocentric and exocentric RGB video from Ego4D, EPIC-KITCHENS, and VidOR',
    output: 'pixel-grounded temporal scene graphs, panoptic mask tubes, object identities, and 57 relation classes',
  }, {
    signals: ['RGB', 'Ego–exo'],
    tasks: ['Perception'],
    scenes: ['Mixed / in-the-wild'],
    sceneCoverage: 'Dynamic scenes drawn from Ego4D, EPIC-KITCHENS, and VidOR',
    sequenceDuration: {unit: 'video', average: '76.5 s', distribution: 'approximately 8.5 h across 400 videos', basis: 'Reported'},
    camera: 'mixed first- and third-person RGB',
    cameraView: 'Mixed / variable',
    capabilities: ['Understanding / recognition', 'Tracking / localization', 'Data capture / annotation'],
    dataProvenance: ['Real capture'],
    inputGroups: ['RGB / video'],
    outputGroups: ['Dataset / labels', 'Perception / tracking', 'Benchmark / evaluation'],
    benchmarks: ['Ego4D', 'EPIC-KITCHENS'],
  }),
  entry({
    name: 'GTEA',
    url: 'https://doi.org/10.1109/CVPR.2011.5995444',
    venue: 'CVPR 2011',
    kinds: ['Dataset'],
    release: '2011',
    access: 'Open dataset',
    accessGroup: 'Open',
    scale: '28 videos; 7 activities; 4 subjects; 15 fps',
    input: 'scripted first-person RGB recordings of kitchen and meal-preparation activities',
    output: 'frame-wise labels for 71 action classes and hand masks',
  }, {
    signals: ['RGB'],
    tasks: ['Manipulation', 'Perception'],
    scenes: ['Indoor', 'Kitchen / household'],
    sceneCoverage: 'Scripted kitchen and meal-preparation activities',
    sequenceDuration: {unit: 'video', distribution: '28 videos across seven activities and four subjects', basis: 'Reported'},
    camera: 'egocentric RGB',
    cameraView: 'Monocular',
    capabilities: ['Understanding / recognition', 'Data capture / annotation'],
    dataProvenance: ['Real capture'],
    inputGroups: ['RGB / video', 'Human demonstration'],
    outputGroups: ['Dataset / labels', 'Benchmark / evaluation'],
  }),
  entry({
    name: 'TACO',
    url: 'https://arxiv.org/abs/2401.08399',
    venue: 'arXiv 2024',
    kinds: ['Dataset'],
    release: '2024',
    access: 'Open dataset and project',
    accessGroup: 'Open',
    scale: '2,500 video sequences; mean robot trajectory 327.5 timesteps; wall-clock duration not reported',
    input: 'egocentric bimanual tool–action–object videos',
    output: 'tool, action, and object understanding benchmark; EgoEngine uses 16 selected demonstration pairs',
  }, {
    signals: ['RGB', '3D / pose'],
    tasks: ['Manipulation', 'Perception'],
    scenes: ['Tabletop / workbench'],
    sceneCoverage: 'Bimanual, object-centric tabletop manipulation',
    sequenceDuration: {unit: 'video', distribution: '2,500 video sequences; wall-clock duration not reported', basis: 'Reported'},
    camera: 'egocentric RGB',
    cameraView: 'Monocular',
    robotInterfaces: ['Bimanual'],
    capabilities: ['Understanding / recognition', 'Data capture / annotation'],
    dataProvenance: ['Real capture'],
    inputGroups: ['RGB / video', 'Hand / body pose', 'Human demonstration'],
    outputGroups: ['Dataset / labels', 'Benchmark / evaluation'],
  }),
  entry({
    name: 'EgoEngine authors’ Aria collection',
    url: 'https://arxiv.org/abs/2606.12604',
    venue: 'EgoEngine · 2026',
    kinds: ['Dataset'],
    release: '2026',
    access: 'Not released',
    accessGroup: 'Announced',
    scale: '200 real-world egocentric human videos across four tasks',
    input: 'Aria Gen 2 RGB video with per-frame 3D hand pose, known object mesh, estimated depth and masks, and AprilTag alignment',
    output: 'private source collection used for EgoEngine’s main real-world evaluation',
  }, {
    signals: ['RGB', '3D / pose'],
    tasks: ['Manipulation', 'Perception'],
    scenes: ['Indoor', 'Tabletop / workbench'],
    sceneCoverage: 'Mustard, Drawer, Hammer, and Flower tasks',
    sequenceDuration: {unit: 'video', distribution: '200 videos; wall-clock duration not reported', basis: 'Reported'},
    camera: 'Meta Aria Gen 2',
    cameraGroup: 'Calibration / intrinsics',
    cameraView: 'Monocular',
    captureDevices: ['Meta Aria'],
    capabilities: ['Reconstruction / geometry', 'Tracking / localization', 'Data capture / annotation'],
    dataProvenance: ['Real capture'],
    inputGroups: ['RGB / video', 'Depth / RGB-D', 'Hand / body pose', 'Human demonstration'],
    outputGroups: ['Dataset / labels', '3D geometry / map', 'Camera / trajectory'],
  }),
  entry({
    name: 'EgoEngine robot teleoperation reference',
    url: 'https://arxiv.org/abs/2606.12604',
    venue: 'EgoEngine · 2026',
    kinds: ['Dataset'],
    release: '2026',
    access: 'Not released',
    accessGroup: 'Announced',
    scale: '200 real-robot demonstrations; duration not reported',
    input: 'robot teleoperation demonstrations',
    output: 'real-observation comparison and sample-efficiency reference; not used as EgoEngine input or training data',
  }, {
    signals: ['Robot action'],
    tasks: ['Manipulation', 'Teleoperation'],
    scenes: ['Tabletop / workbench'],
    sceneCoverage: 'Real-robot evaluation tasks',
    sequenceDuration: {unit: 'trajectory', distribution: '200 demonstrations; duration not reported', basis: 'Reported'},
    referenceTags: ['Robot reference'],
    capabilities: ['Data capture / annotation'],
    dataProvenance: ['Real capture'],
    systemLayers: ['Data / runtime'],
    inputGroups: ['Robot state / action', 'Human demonstration'],
    outputGroups: ['Robot actions / demos', 'Benchmark / evaluation'],
  }),
  entry({
    name: 'Lucida',
    url: 'https://lucida-r2s.github.io/',
    venue: 'arXiv 2026',
    kinds: ['Pipeline'],
    release: '2026',
    access: 'Paper and project page; code not verified',
    accessGroup: 'Paper / code',
    scale: 'posed multiview observations of a real indoor scene; sequence count not reported',
    input: 'posed multiview RGB observations',
    output: 'instance scene graph, complete editable assets, and a composable simulation-ready scene',
  }, {
    signals: ['RGB', '3D / pose', 'Language'],
    tasks: ['Perception', 'Generation / world model'],
    scenes: ['Indoor', 'Room-scale / building'],
    sceneCoverage: 'Static real indoor arrangements',
    camera: 'posed multiview observations',
    cameraGroup: 'Calibration / intrinsics',
    cameraView: 'Multi-camera / multiview',
    capabilities: ['Reconstruction / geometry', 'Simulation'],
    dataProvenance: ['Real capture', 'Hybrid real + rerender'],
    referenceTags: ['Robot reference'],
    renderMethods: ['3D engine / simulator'],
    geometryLayers: ['Object reconstruction', 'Scene / environment reconstruction'],
    systemLayers: ['Perception / state estimation', 'Simulation / rendering'],
    inputGroups: ['RGB / video', 'Multiview'],
    outputGroups: ['3D geometry / map'],
  }),
  entry({
    name: 'VideoMimic',
    url: 'https://www.videomimic.net/',
    venue: 'CoRL 2025',
    kinds: ['Pipeline', 'Policy'],
    release: '2025',
    access: 'Open code',
    accessGroup: 'Open',
    scale: 'single-camera RGB video; reported corpus size varies by source video',
    input: 'monocular human RGB video',
    output: 'world-scale human pose and contact, reconstructed scene geometry, humanoid retargeting, and a scene-conditioned control policy',
  }, {
    signals: ['RGB', '3D / pose', 'Contact', 'Robot action'],
    tasks: ['Locomotion', 'Human motion', 'Teleoperation'],
    scenes: ['Mixed / in-the-wild'],
    sceneCoverage: 'Scene-conditioned whole-body skills from arbitrary source videos',
    camera: 'single-camera RGB',
    cameraView: 'Monocular',
    robotInterfaces: ['Humanoid / whole-body'],
    capabilities: ['Reconstruction / geometry', 'Retargeting / embodiment transfer', 'Policy learning / control'],
    dataProvenance: ['Real capture', 'Synthetic simulation'],
    referenceTags: ['Robot reference'],
    geometryLayers: ['Body reconstruction', 'Scene / environment reconstruction', 'Physics / dynamics'],
    systemLayers: ['Perception / state estimation', 'Simulation / rendering', 'Physical / embodiment', 'Planning / control', 'RL / training infrastructure'],
    components: ['Retargeting'],
    componentFamilies: ['Retargeting / IK', 'Human body / hand'],
    inputGroups: ['RGB / video', 'Human demonstration'],
    outputGroups: ['Hand / body motion', '3D geometry / map', 'Policy / control'],
  }),
  entry({
    name: 'Real2Render2Real',
    url: 'https://real2render2real.com/',
    venue: 'arXiv 2025',
    kinds: ['Dataset', 'Pipeline'],
    release: '2025',
    access: 'Open code',
    accessGroup: 'Open',
    scale: 'phone scan and one human demonstration; thousands of rendered robot trajectories',
    input: 'smartphone scene scan and one human demonstration',
    output: 'Gaussian scene converted to a simulator-compatible mesh and a large rendered robot demonstration set',
  }, {
    signals: ['RGB', '3D / pose', 'Robot action'],
    tasks: ['Manipulation', 'Teleoperation', 'Generation / world model'],
    scenes: ['Indoor', 'Tabletop / workbench'],
    sceneCoverage: 'Scene-specific robot manipulation',
    camera: 'smartphone scan',
    cameraView: 'Monocular',
    captureDevices: ['iPhone / smartphone'],
    capabilities: ['Reconstruction / geometry', 'Rendering / novel view', 'Simulation', 'Retargeting / embodiment transfer', 'Data capture / annotation'],
    dataProvenance: ['Real capture', 'Hybrid real + rerender'],
    referenceTags: ['Robot reference'],
    renderMethods: ['View translation / neural rendering'],
    geometryLayers: ['Scene / environment reconstruction'],
    systemLayers: ['Perception / state estimation', 'Simulation / rendering', 'Physical / embodiment'],
    inputGroups: ['RGB / video', 'Hand / body pose', 'Human demonstration'],
    outputGroups: ['3D geometry / map', 'Robot actions / demos', 'Generated media'],
  }),
  entry({
    name: 'InternVLA-A1 / InternData-A1',
    url: 'https://internrobotics.github.io/internvla-a1.github.io/',
    venue: '2026 / 2025',
    kinds: ['Dataset', 'Pipeline', 'Policy'],
    release: '2026',
    access: 'Open data and project',
    accessGroup: 'Open',
    scale: '630K synthetic trajectories (7,433 h); 227 scenes; 4 embodiments; 18 skills; 70 tasks; combined pretraining exceeds 533M frames',
    input: 'heterogeneous real and synthetic robot observations, language, and actions',
    output: 'unified understanding, generation, and action model plus InternData-A1 training corpus',
  }, {
    signals: ['RGB', '3D / pose', 'Language', 'Robot action'],
    tasks: ['Manipulation', 'Generation / world model'],
    scenes: ['Tabletop / workbench', 'Synthetic / simulation'],
    sceneCoverage: 'Rigid, articulated, deformable, and fluid interactions',
    robotInterfaces: ['Single-arm / single-hand', 'Bimanual'],
    capabilities: ['Understanding / recognition', 'Generation / world model', 'Simulation', 'Policy learning / control', 'Data capture / annotation'],
    dataProvenance: ['Real capture', 'Synthetic simulation'],
    referenceTags: ['Robot reference'],
    systemLayers: ['Simulation / rendering', 'Planning / control', 'Data / runtime', 'World model / synthetic data'],
    inputGroups: ['RGB / video', 'Language', 'Robot state / action', 'Synthetic / simulation'],
    outputGroups: ['Dataset / labels', 'Robot actions / demos', 'Policy / control', 'Generated media'],
  }),
  entry({
    name: 'RoboTwin 2.0',
    url: 'https://robotwin-platform.github.io/',
    venue: 'ICML 2026',
    kinds: ['Dataset', 'Pipeline'],
    release: '2026',
    access: 'Open code and data',
    accessGroup: 'Open',
    scale: '50 dual-arm tasks; 5 embodiments; 731 objects in 147 categories; more than 100K released trajectories',
    input: 'known simulator geometry, task specifications, and domain-randomized robot state',
    output: 'automatically synthesized task code, simulation-in-the-loop refinement, benchmark tasks, and robot trajectories',
  }, {
    signals: ['RGB', '3D / pose', 'Language', 'Robot action'],
    tasks: ['Manipulation', 'Generation / world model'],
    scenes: ['Tabletop / workbench', 'Synthetic / simulation'],
    sceneCoverage: 'Dual-arm manipulation with randomized clutter, lighting, backgrounds, and table heights',
    sequenceDuration: {unit: 'trajectory', distribution: 'task-dependent caps of 200, 400, or 800 steps; wall-clock duration not reported', basis: 'Reported'},
    robotInterfaces: ['Bimanual'],
    capabilities: ['Simulation', 'Policy learning / control', 'Data capture / annotation'],
    dataProvenance: ['Synthetic simulation'],
    referenceTags: ['Robot reference'],
    renderMethods: ['3D engine / simulator'],
    systemLayers: ['Simulation / rendering', 'Planning / control', 'RL / training infrastructure', 'World model / synthetic data'],
    inputGroups: ['Language', 'Robot state / action', 'Synthetic / simulation'],
    outputGroups: ['Robot actions / demos', 'Benchmark / evaluation'],
  }),
  entry({
    name: 'SoftMimicGen',
    url: 'https://softmimicgen.github.io/',
    venue: 'ICRA 2026',
    kinds: ['Dataset', 'Pipeline'],
    release: '2026',
    access: 'Open code',
    accessGroup: 'Open',
    scale: 'four embodiments; 1–3 source demonstrations generate 1,000 episodes per task',
    input: 'task-ready simulation environments and a small number of robot demonstrations',
    output: 'synthetic demonstrations for deformable-object manipulation',
  }, {
    signals: ['3D / pose', 'Contact', 'Robot action'],
    tasks: ['Manipulation', 'Generation / world model'],
    scenes: ['Tabletop / workbench', 'Synthetic / simulation'],
    sceneCoverage: 'Stuffed animals, ropes, tissues, towels, threading, whipping, folding, and pick-and-place',
    sequenceDuration: {unit: 'episode', distribution: '1,000 generated episodes per task; wall-clock duration not reported', basis: 'Reported'},
    robotInterfaces: ['Single-arm / single-hand', 'Bimanual'],
    capabilities: ['Simulation', 'Policy learning / control', 'Data capture / annotation'],
    dataProvenance: ['Synthetic simulation'],
    referenceTags: ['Robot reference'],
    renderMethods: ['3D engine / simulator'],
    geometryLayers: ['Physics / dynamics'],
    systemLayers: ['Simulation / rendering', 'RL / training infrastructure', 'World model / synthetic data'],
    inputGroups: ['Robot state / action', 'Human demonstration', 'Synthetic / simulation'],
    outputGroups: ['Robot actions / demos', 'Generated media'],
  }),
  entry({
    name: 'Re3Sim',
    url: 'https://xshenhan.github.io/Re3Sim/',
    venue: 'ICRA 2026',
    kinds: ['Dataset', 'Pipeline'],
    release: '2026',
    access: 'Open code',
    accessGroup: 'Open',
    scale: 'captured task scenes and large-scale simulated rollouts; sequence count not reported',
    input: 'multiview captures of real robot task scenes',
    output: 'cross-view neural rendering inside a physics simulator and photorealistic simulated rollouts',
  }, {
    signals: ['RGB', '3D / pose', 'Robot action'],
    tasks: ['Manipulation', 'Generation / world model'],
    scenes: ['Tabletop / workbench', 'Synthetic / simulation'],
    sceneCoverage: 'Individual captured robot-task scenes',
    camera: 'cross-view multiview capture',
    cameraGroup: 'Calibration / intrinsics',
    cameraView: 'Multi-camera / multiview',
    capabilities: ['Reconstruction / geometry', 'Rendering / novel view', 'Simulation', 'Data capture / annotation'],
    dataProvenance: ['Real capture', 'Hybrid real + rerender', 'Synthetic simulation'],
    referenceTags: ['Robot reference'],
    renderMethods: ['3D engine / simulator', 'View translation / neural rendering'],
    geometryLayers: ['Scene / environment reconstruction', 'Physics / dynamics'],
    systemLayers: ['Simulation / rendering', 'World model / synthetic data'],
    inputGroups: ['RGB / video', 'Multiview', 'Robot state / action'],
    outputGroups: ['Robot actions / demos', 'Generated media'],
  }),
  entry({
    name: 'GSWorld',
    url: 'https://3dgsworld.github.io/',
    venue: 'ICRA 2026',
    kinds: ['Pipeline'],
    release: '2026',
    access: 'Open code',
    accessGroup: 'Open',
    scale: '3 robot embodiments and more than 40 objects',
    input: 'captured robot scenes and actions',
    output: 'Gaussian-on-mesh appearance with signed-distance geometry and URDF dynamics for closed-loop simulation',
  }, {
    signals: ['RGB', '3D / pose', 'Robot action'],
    tasks: ['Manipulation', 'Generation / world model'],
    scenes: ['Tabletop / workbench', 'Synthetic / simulation'],
    sceneCoverage: 'Photorealistic closed-loop robot manipulation',
    capabilities: ['Reconstruction / geometry', 'Rendering / novel view', 'Simulation'],
    dataProvenance: ['Real capture', 'Hybrid real + rerender'],
    referenceTags: ['Robot reference'],
    renderMethods: ['3D engine / simulator', 'View translation / neural rendering'],
    geometryLayers: ['Object reconstruction', 'Scene / environment reconstruction', 'Physics / dynamics'],
    systemLayers: ['Simulation / rendering', 'Physical / embodiment'],
    inputGroups: ['RGB / video', 'Robot state / action'],
    outputGroups: ['3D geometry / map', 'Generated media'],
  }),
  entry({
    name: 'RoboVIP',
    url: 'https://robovip.github.io/RoboVIP/',
    venue: 'arXiv 2026',
    kinds: ['Pipeline', 'General model'],
    release: '2026',
    access: 'Open code',
    accessGroup: 'Open',
    scale: 'multiview robot videos; scale and sequence length inherit each source dataset',
    input: 'multiview robot videos and visual identity conditioning',
    output: 'temporally coherent, action-preserving video augmentation',
  }, {
    signals: ['RGB', 'Ego–exo', 'Robot action'],
    tasks: ['Manipulation', 'Generation / world model'],
    scenes: ['Mixed / in-the-wild'],
    sceneCoverage: 'Source-dataset robot scenes',
    camera: 'multiview robot video',
    cameraView: 'Multi-camera / multiview',
    capabilities: ['Rendering / novel view', 'Generation / world model'],
    dataProvenance: ['Real capture', 'Generated video'],
    referenceTags: ['Robot reference'],
    renderMethods: ['Video diffusion / world model', 'View translation / neural rendering'],
    systemLayers: ['Simulation / rendering', 'World model / synthetic data'],
    inputGroups: ['RGB / video', 'Multiview', 'Robot state / action'],
    outputGroups: ['Generated media'],
  }),
  entry({
    name: 'RoboSnap',
    url: 'https://robosnap.github.io/',
    venue: 'arXiv 2026',
    kinds: ['Dataset', 'Pipeline'],
    release: '2026',
    access: 'Code available; companion DROID-Sim dataset not released',
    accessGroup: 'Paper / code',
    scale: 'one RGB image per scene; DROID-Sim contains 564 reconstructed real scenes',
    input: 'single RGB image',
    output: 'collision-aware foreground objects, a 3D-Gaussian background, and simulator-ready one-shot scenes',
  }, {
    signals: ['RGB', '3D / pose'],
    tasks: ['Manipulation', 'Perception', 'Generation / world model'],
    scenes: ['Tabletop / workbench', 'Synthetic / simulation'],
    sceneCoverage: 'Reconstructed real robot scenes',
    camera: 'single RGB image',
    cameraView: 'Monocular',
    capabilities: ['Reconstruction / geometry', 'Rendering / novel view', 'Simulation'],
    dataProvenance: ['Real capture', 'Hybrid real + rerender'],
    referenceTags: ['Robot reference'],
    renderMethods: ['3D engine / simulator', 'View translation / neural rendering'],
    geometryLayers: ['Object reconstruction', 'Scene / environment reconstruction', 'Physics / dynamics'],
    systemLayers: ['Perception / state estimation', 'Simulation / rendering'],
    inputGroups: ['RGB / video'],
    outputGroups: ['3D geometry / map', 'Generated media'],
  }),
  entry({
    name: 'IGen',
    url: 'https://chenghaogu.github.io/IGen/',
    venue: 'CVPR 2026',
    kinds: ['Dataset', 'Pipeline'],
    release: '2026',
    access: 'Project announced; code and data not released',
    accessGroup: 'Announced',
    scale: 'one image and task prompt; up to 1,000 demonstrations generated from an image',
    input: 'single open-world image and task prompt',
    output: 'image- and point-cloud-conditioned scene generation, VLM planning, simulated execution, and robot demonstrations',
  }, {
    signals: ['RGB', '3D / pose', 'Language', 'Robot action'],
    tasks: ['Manipulation', 'Generation / world model'],
    scenes: ['Tabletop / workbench', 'Synthetic / simulation'],
    sceneCoverage: 'Open-world static observations converted to robot task scenes',
    camera: 'single RGB image',
    cameraView: 'Monocular',
    capabilities: ['Reconstruction / geometry', 'Generation / world model', 'Simulation', 'Policy learning / control', 'Data capture / annotation'],
    dataProvenance: ['Real capture', 'Synthetic simulation'],
    referenceTags: ['Robot reference'],
    renderMethods: ['3D engine / simulator'],
    geometryLayers: ['Object reconstruction', 'Scene / environment reconstruction', 'Physics / dynamics'],
    systemLayers: ['Perception / state estimation', 'Simulation / rendering', 'Planning / control', 'World model / synthetic data'],
    inputGroups: ['RGB / video', 'Language'],
    outputGroups: ['3D geometry / map', 'Robot actions / demos', 'Generated media'],
  }),
];
