'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';

type Maturity='Foundation'|'Production'|'Frontier'|'Governance';
type Layer='Embodiment'|'Sensing'|'Control'|'Data'|'Simulation'|'Policy'|'Agency'|'Evaluation'|'Safety'|'Operations';
type Topic={
  name:string; layer:Layer; maturity:Maturity; signal:string; must:string; stack:string;
  owner:string; mistake:string; source:string; url:string; links?:{name:string;href:string}[];
};

const layerMeta:{name:Layer;code:string;purpose:string;question:string;color:string}[]=[
  {name:'Embodiment',code:'L01',purpose:'Bodies, actuators, hands and workcells',question:'What can physically touch the world?',color:'#ff6337'},
  {name:'Sensing',code:'L02',purpose:'Perception, calibration and state',question:'What is observed, synchronized and localized?',color:'#ef9d33'},
  {name:'Control',code:'L03',purpose:'Kinematics, dynamics and real-time loops',question:'What turns a desired motion into stable force?',color:'#d8f432'},
  {name:'Data',code:'L04',purpose:'Demonstrations, teleop and schemas',question:'What experience is captured and reusable?',color:'#66bd74'},
  {name:'Simulation',code:'L05',purpose:'Worlds, twins and transfer',question:'What can be generated, replayed and varied?',color:'#48a9a6'},
  {name:'Policy',code:'L06',purpose:'Representations, backbones and actions',question:'What maps observations to robot behavior?',color:'#4a7fe8'},
  {name:'Agency',code:'L07',purpose:'Planning, memory and recovery',question:'What keeps a goal alive across time?',color:'#685ee8'},
  {name:'Evaluation',code:'L08',purpose:'Tasks, metrics and causal diagnosis',question:'What evidence means the system improved?',color:'#9a60c7'},
  {name:'Safety',code:'L09',purpose:'Hazards, assurance and standards',question:'What bounds failure before deployment?',color:'#d95b83'},
  {name:'Operations',code:'L10',purpose:'Fleet, reliability and economics',question:'What makes the robot a durable product?',color:'#17201b'},
];

const topics:Topic[]=[
  {name:'Frames, kinematics & reachability',layer:'Embodiment',maturity:'Foundation',signal:'SE(3) transforms · Jacobians · singularities',must:'Every camera, tool and action lives in a coordinate frame. Forward/inverse kinematics define what poses are reachable; Jacobians connect joint velocity to Cartesian motion.',stack:'URDF / MJCF · Pinocchio · Drake',owner:'Version robot geometry, tool-center-point and calibration together with every dataset.',mistake:'Treating “end-effector XYZ” as portable without naming frame, convention, units and timestamp.',source:'Pinocchio documentation',url:'https://stack-of-tasks.github.io/pinocchio/'},
  {name:'Actuation, gearing & compliance',layer:'Embodiment',maturity:'Production',signal:'Torque · position · impedance · bandwidth',must:'Motors, transmissions and joint elasticity determine usable force, backdrivability, accuracy and control bandwidth—not the policy checkpoint.',stack:'Servo drives · harmonic/cycloidal gears · SEA/QDD',owner:'Record command mode, gains, limits, thermal state and measured joint response.',mistake:'Comparing policies across arms while hiding low-level controller and payload differences.',source:'ros2_control documentation',url:'https://control.ros.org/'},
  {name:'End-effectors & dexterity',layer:'Embodiment',maturity:'Production',signal:'Parallel jaw · suction · anthropomorphic hand',must:'The end-effector is a task prior. Simple grippers offer reliable contact; dexterous hands expand behaviors but multiply sensing, calibration and data burden.',stack:'Grippers · tool changers · tactile hands',owner:'Choose the simplest contact geometry that covers the product task distribution.',mistake:'Calling an embodiment “general” while evaluating only tasks aligned to one gripper.',source:'Yale OpenHand Project',url:'https://www.eng.yale.edu/grablab/openhand/'},
  {name:'Mobile bases & whole-body reach',layer:'Embodiment',maturity:'Production',signal:'Base + arm + torso + balance',must:'Mobility turns a tabletop policy into a spatial system. Base placement, collision envelopes and coordinated whole-body control affect every manipulation episode.',stack:'Nav2 · mobile manipulators · humanoids',owner:'Log base pose, local map, support state and whole-body command—not arm joints alone.',mistake:'Measuring long-horizon success in a pre-positioned workcell and generalizing to a home.',source:'ROS 2 Navigation',url:'https://docs.nav2.org/'},
  {name:'Locomotion, balance & fall recovery',layer:'Embodiment',maturity:'Frontier',signal:'Contacts · centroidal dynamics · gait · terrain',must:'Legged mobility couples estimation, impacts, thermal limits and whole-body control. Nominal walking is easier than robust recovery while carrying or manipulating.',stack:'Isaac Lab · MuJoCo Playground · HumanoidBench',owner:'Track falls, pushes, terrain shifts, current/thermal margin and autonomous recovery—not reward alone.',mistake:'Treating a stable simulator video as evidence of field deployability.',source:'HumanoidBench',url:'https://humanoid-bench.github.io/'},

  {name:'Calibration & time synchronization',layer:'Sensing',maturity:'Foundation',signal:'Intrinsics · extrinsics · clock offset · latency',must:'Millimeters of extrinsic error or tens of milliseconds of skew can look like a learning failure. Calibration is part of the data contract.',stack:'Camera models · PTP · hardware triggers · TF2',owner:'Track calibration residuals and clock health per session; reject bad capture automatically.',mistake:'Storing calibrated tensors but not the raw stream, calibration version or clock domain.',source:'ROS 2 tf2',url:'https://docs.ros.org/en/jazzy/Concepts/Intermediate/About-Tf2.html'},
  {name:'State estimation, SLAM & 3D maps',layer:'Sensing',maturity:'Production',signal:'Pose · map · uncertainty · relocalization',must:'A robot acting beyond one camera view needs persistent spatial state. Visual-inertial odometry, SLAM and mapping create the coordinate substrate for revisit and recovery.',stack:'VIO · factor graphs · TSDF / splats · MPS',owner:'Expose uncertainty, map revisions and relocalization events to planners and evaluators.',mistake:'Using a beautiful reconstruction as if it were metrically stable, current and collision-safe.',source:'Project Aria Machine Perception Services',url:'https://www.projectaria.com/'},
  {name:'Tactile, force & contact state',layer:'Sensing',maturity:'Frontier',signal:'Normal/shear force · slip · contact geometry',must:'Vision often cannot observe incipient slip, insertion force or occluded contact. Tactile and force sensing close the loop at the interaction surface.',stack:'F/T sensors · GelSight/DIGIT · taxels · proprioception',owner:'Synchronize raw tactile, calibrated wrench, contact events and control state.',mistake:'Adding tactile hardware without an annotation, calibration and policy-integration plan.',source:'DIGIT tactile sensor',url:'https://digit.ml/' ,links:[{name:'Tactile atlas',href:'/#tactile'}]},
  {name:'Perception representations',layer:'Sensing',maturity:'Frontier',signal:'RGB-D · points · voxels · objects · affordances',must:'Semantic features answer “what”; geometry answers “where”; contact affordances answer “how.” Production stacks usually need more than one representation.',stack:'DINO / SigLIP · depth · point clouds · scene graphs',owner:'Audit which spatial information survives the encoder and at what update rate.',mistake:'Assuming a larger VLM automatically preserves millimeter-scale geometry.',source:'Open3D',url:'https://www.open3d.org/'},

  {name:'Dynamics & contact mechanics',layer:'Control',maturity:'Foundation',signal:'Mass · inertia · friction · impacts · constraints',must:'Manipulation is governed by coupled rigid-body dynamics and discontinuous contacts. Stable control and faithful simulation depend on the same physical quantities.',stack:'MuJoCo · Drake · SAPIEN · Isaac Lab',owner:'Maintain payload, friction and actuator models with confidence ranges—not single magic constants.',mistake:'Explaining every transfer failure as “the sim-to-real gap” without identifying which physics is wrong.',source:'MuJoCo documentation',url:'https://mujoco.readthedocs.io/'},
  {name:'Feedback, impedance & force control',layer:'Control',maturity:'Production',signal:'Hz · delay · gains · passivity · saturation',must:'Policies propose behavior; fast controllers keep it stable. Position, velocity, torque and impedance interfaces create materially different action spaces.',stack:'PID · operational-space control · impedance · MPC',owner:'Measure end-to-end observation-to-actuation latency and preserve controller parameters in evaluations.',mistake:'Reporting policy inference rate while ignoring camera age, network delay and inner-loop rate.',source:'Drake manipulation systems',url:'https://manipulation.csail.mit.edu/'},
  {name:'Motion planning & collision checking',layer:'Control',maturity:'Production',signal:'Geometric path · trajectory · constraints',must:'Classical planners remain strong for known geometry, safety envelopes and goal-conditioned transit. Learned skills and planners are complements.',stack:'MoveIt 2 · OMPL · trajectory optimization',owner:'Define when the learned policy, planner or safety controller has authority.',mistake:'Forcing a VLA to relearn deterministic collision-free transit or hard limits from demonstrations.',source:'MoveIt 2',url:'https://moveit.picknik.ai/main/index.html'},
  {name:'Skill interfaces & hybrid control',layer:'Control',maturity:'Frontier',signal:'Modes · guards · options · recovery',must:'Real tasks mix free-space motion, contact, tools and navigation. Hybrid systems make mode changes and guard conditions explicit.',stack:'Behavior trees · state machines · learned options',owner:'Instrument transition causes, preconditions, termination and recovery outcomes.',mistake:'A monolithic policy with no inspectable boundary between task state and motor state.',source:'BehaviorTree.CPP',url:'https://www.behaviortree.dev/'},

  {name:'Robot demonstration datasets',layer:'Data',maturity:'Production',signal:'Observation · action · state · language · embodiment',must:'Robot trajectories provide executable actions but remain expensive and embodiment-specific. Schema quality and coverage matter as much as hours.',stack:'DROID · Bridge · OXE · Open X-Embodiment',owner:'Count task diversity, failures, operators and environments—not only episodes.',mistake:'Adding heterogeneous data without action normalization, embodiment tokens or provenance.',source:'Open X-Embodiment',url:'https://robotics-transformer-x.github.io/',links:[{name:'Data atlas',href:'/#atlas'}]},
  {name:'Teleoperation & intervention capture',layer:'Data',maturity:'Production',signal:'Bimanual · VR · leader-follower · UMI',must:'Teleop determines throughput, operator strain, action quality and which embodiments can be covered. Interventions are especially valuable recovery supervision.',stack:'ALOHA · UMI · VR controllers · exoskeletons',owner:'Measure setup time, usable episode yield, intervention burden and operator learning effects.',mistake:'Calling raw recording hours “training hours” without quality yield and reset labor.',source:'Universal Manipulation Interface',url:'https://umi-gripper.github.io/'},
  {name:'Egocentric human experience',layer:'Data',maturity:'Frontier',signal:'Hands · objects · intent · workflow · gaze · audio',must:'First-person video scales procedural and contextual coverage but usually lacks robot actions and calibrated 3D contact. It is a pretraining substrate, not automatically a policy dataset.',stack:'Ego4D · Project Aria · Ego-Exo4D · Ego4D',owner:'Separate semantic/procedural value from action-supervision value and quantify the conversion gap.',mistake:'Treating video hours as equivalent to state-action trajectory hours.',source:'Ego-Exo4D',url:'https://ego-exo4d-data.org/',links:[{name:'Capability topology',href:'/#matrix'}]},
  {name:'Dataset schemas, lineage & quality',layer:'Data',maturity:'Governance',signal:'Episodes · timestamps · transforms · licenses · checksums',must:'A dataset is a governed product: immutable raw signals, versioned derived artifacts, lineage, quality tests, access policy and deletion paths.',stack:'LeRobotDataset · RLDS · Parquet · object storage',owner:'Publish a data contract and automate clock, calibration, dropout, action and success checks.',mistake:'Keeping “the dataset” as folders whose semantics live only in collector knowledge.',source:'LeRobot dataset format',url:'https://huggingface.co/docs/lerobot/lerobot-dataset-v3'},

  {name:'Simulation substrates',layer:'Simulation',maturity:'Production',signal:'Physics · sensors · assets · parallelism · determinism',must:'Simulation is useful for controlled coverage, counterfactuals and regression. Simulator choice couples physics fidelity, speed, sensors and tooling.',stack:'MuJoCo · Isaac Lab · ManiSkill · robosuite · Genesis',owner:'Choose fidelity from the failure mode and publish the simulator/version/asset contract.',mistake:'Reporting millions of episodes without sim-real correlation or asset diversity.',source:'Isaac Lab',url:'https://isaac-sim.github.io/IsaacLab/'},
  {name:'Domain randomization & adaptation',layer:'Simulation',maturity:'Production',signal:'Appearance · dynamics · latency · sensor noise',must:'Randomization can create robustness when ranges cover real variation. Too broad wastes capacity; too narrow produces brittle policies.',stack:'System identification · randomization · adaptation',owner:'Fit distributions from real measurements and track which nuisance variables drive transfer.',mistake:'Randomizing everything uniformly rather than modeling correlated, measured uncertainty.',source:'NVIDIA Isaac Lab sim-to-real',url:'https://isaac-sim.github.io/IsaacLab/main/source/tutorials/03_envs/create_manager_rl_env.html'},
  {name:'Real2Sim & digital twins',layer:'Simulation',maturity:'Frontier',signal:'Video → geometry → motion → physics → replay',must:'Reconstruction spans appearance twins through executable, policy-valid episode twins. Geometry alone is not a robot-learning environment.',stack:'NeRF/3DGS · tracking · contact recovery · physics ID',owner:'Require metric scale, articulations, contacts, collision geometry and replay validation for policy use.',mistake:'Calling a novel-view renderer a physics-ready digital twin.',source:'Real2Sim workbench',url:'/real2sim',links:[{name:'Open workbench',href:'/real2sim'}]},
  {name:'Synthetic data & world generation',layer:'Simulation',maturity:'Frontier',signal:'Assets · scenes · trajectories · labels · variation',must:'Generative worlds can expand the tail of geometry and tasks, but controllability, physical validity and evaluation leakage remain open problems.',stack:'Procedural assets · generative 3D · video-to-world',owner:'Tag synthetic provenance and validate every generated label or trajectory against executable constraints.',mistake:'Confusing photorealism with correct contact, dynamics or task distribution.',source:'NVIDIA Isaac Sim Replicator',url:'https://docs.isaacsim.omniverse.nvidia.com/latest/replicator_tutorials/index.html'},

  {name:'Behavior cloning & action chunking',layer:'Policy',maturity:'Production',signal:'History → continuous action sequence',must:'Supervised imitation remains the dependable baseline. Action chunks reduce compounding autoregressive error and amortize inference, but can delay reactions.',stack:'ACT · transformer policies · receding horizon',owner:'Tune prediction, execution and replan horizons independently; log intervention and recovery.',mistake:'Equating a long predicted chunk with long-horizon task understanding.',source:'ALOHA / ACT',url:'https://tonyzhaozh.github.io/aloha/',links:[{name:'Architecture workbench',href:'/model-architectures'}]},
  {name:'Diffusion & flow action heads',layer:'Policy',maturity:'Production',signal:'Multimodal continuous trajectory distribution',must:'Generative action heads represent multiple valid motions and smooth trajectories. Sampling latency, normalization and closed-loop cadence are first-class constraints.',stack:'Diffusion Policy · flow matching · DiT',owner:'Benchmark wall-clock control rate and success at the deployed denoising budget.',mistake:'Comparing offline action loss while ignoring rollout stability and inference latency.',source:'Diffusion Policy',url:'https://diffusion-policy.cs.columbia.edu/'},
  {name:'Vision-language-action foundation models',layer:'Policy',maturity:'Frontier',signal:'Images + language + state → actions',must:'VLAs transfer semantic priors and multi-task behavior, but action heads, robot data and post-training determine usable control. “VLA” is not one architecture.',stack:'OpenVLA · π0 · GR00T · Gemini Robotics · LingBot',owner:'Audit training data, action representation, supported embodiments, latency and evaluation protocol.',mistake:'Ranking models by parameter count or mixing scores from incompatible benchmarks.',source:'OpenVLA',url:'https://openvla.github.io/',links:[{name:'Model registry',href:'/model-architectures'}]},
  {name:'Zero-shot transfer contracts',layer:'Policy',maturity:'Governance',signal:'No target examples · no target update · named novelty axis',must:'“Zero-shot” is meaningful only after naming what is unseen: instruction, object, scene, task, embodiment or dynamics. A model can be zero-shot on one axis and heavily trained on the others.',stack:'Frozen checkpoint · held-out split · contamination audit',owner:'Publish the target boundary, related training exposure, prompt engineering and every test-time adaptation.',mistake:'Calling a new object position or paraphrased instruction a zero-shot new skill.',source:'RT-2 project',url:'https://robotics-transformer2.github.io/',links:[{name:'Transfer regimes',href:'/model-architectures#transfer-regimes'}]},
  {name:'In-context robot learning',layer:'Policy',maturity:'Frontier',signal:'Demonstration prompt + current state → action · no weight update',must:'True robot ICL conditions a frozen policy on one or more test-time demonstrations. It normally requires meta-training that teaches the model how context changes the intended behavior.',stack:'ICRT · Instant Policy · RICL · MimicDroid',owner:'Measure prompt count, prompt modality, retrieval, context length, latency and gains over no-context and finetuning baselines.',mistake:'Calling ordinary language conditioning, nearest-neighbor replay or test-time gradient updates “in-context learning.”',source:'ICRT',url:'https://icrt.dev/',links:[{name:'Transfer regimes',href:'/model-architectures#transfer-regimes'}]},
  {name:'Pretraining, post-training & adaptation',layer:'Policy',maturity:'Frontier',signal:'Internet priors → robot priors → task reliability',must:'Pretraining buys breadth; post-training concentrates behavior on an embodiment, environment and reliability target. High-quality failures and recoveries can outweigh undirected scale.',stack:'Co-training · LoRA · full finetune · RL / preference optimization',owner:'Freeze a base-model evaluation, then attribute gains to data mix, adaptation method and selection.',mistake:'Using test-like post-training data or reporting only the best task-specific checkpoint.',source:'Training strategy ledger',url:'/training-strategies',links:[{name:'Training strategies',href:'/training-strategies'}]},

  {name:'Task planning & skill composition',layer:'Agency',maturity:'Frontier',signal:'Goal → subgoals → skills → verification',must:'Long workflows need task-state tracking above reactive motor control. Planners allocate skills, inspect preconditions and revise after failure.',stack:'LLM/VLM planner · behavior tree · skill library',owner:'Separate planner success, skill success and handoff failure in telemetry.',mistake:'Calling a scripted sequence “agency” or blaming the motor policy for a planning error.',source:'SayCan',url:'https://say-can.github.io/'},
  {name:'Spatial-temporal memory & revisit',layer:'Agency',maturity:'Frontier',signal:'Object permanence · episodic events · 3D place memory',must:'A robot must remember where objects were seen, what changed and which attempts failed. Retrieval should be grounded to time, place and uncertainty.',stack:'Metric-semantic map · scene graph · episodic retrieval',owner:'Define memory write, update, confidence, expiry and privacy rules before adding a vector database.',mistake:'Retrieving visually similar frames without grounding them to current geometry or task state.',source:'ConceptGraphs',url:'https://concept-graphs.github.io/'},
  {name:'World models & predictive control',layer:'Agency',maturity:'Frontier',signal:'Action-conditioned future · value · uncertainty',must:'Predictive models can support planning, data generation and failure anticipation, but video plausibility is weaker evidence than action-conditioned physical accuracy.',stack:'Latent dynamics · video prediction · model-based planning',owner:'Evaluate counterfactual accuracy on contacts, state changes and rare failures—not visual quality alone.',mistake:'Treating a generative video model as a simulator without controllable actions or calibrated state.',source:'DreamerV3',url:'https://danijar.com/project/dreamerv3/'},
  {name:'Failure detection, recovery & assistance',layer:'Agency',maturity:'Production',signal:'Detect → diagnose → retry/replan/escalate',must:'Production autonomy is defined by what happens after the nominal policy fails. Detection and safe escalation often matter more than a small headline success-rate gain.',stack:'Critics · monitors · recovery policy · human escalation',owner:'Maintain a failure taxonomy and measure autonomous recovery plus human intervention time.',mistake:'Resetting every failed trial and reporting only fresh-start success.',source:'HoloAssist',url:'https://holoassist.github.io/',links:[{name:'Agency evidence',href:'/#agency-evidence'}]},

  {name:'Benchmark contracts & reproducibility',layer:'Evaluation',maturity:'Governance',signal:'Tasks · resets · trials · seeds · score · confidence',must:'A score is meaningful only inside its protocol. Simulator version, embodiment, observations, control mode, resets and trial count all belong in the result.',stack:'LIBERO · RoboCasa365 · RoboTwin · CALVIN · real arenas',owner:'Store evaluation manifests and per-trial outcomes; never aggregate incomparable boards.',mistake:'Building a global VLA leaderboard by sorting percentages with different denominators.',source:'RoboCasa365 leaderboard',url:'https://robocasa.ai/leaderboard.html',links:[{name:'Leaderboard atlas',href:'/model-architectures'}]},
  {name:'Long-horizon & high-agency evaluation',layer:'Evaluation',maturity:'Frontier',signal:'Progress · success · recovery · intervention · time',must:'Binary final success hides where workflows break. Long-horizon evaluation needs subgoal progress, temporal efficiency, recovery, disturbance and assistance metrics.',stack:'BEHAVIOR-1K · CALVIN chains · GM-100 · open-ended homes',owner:'Publish fresh-start and disturbed-start results with failure stage and intervention accounting.',mistake:'Multiplying atomic skill scores and calling the result a measured long-horizon capability.',source:'BEHAVIOR-1K Challenge',url:'https://behavior.stanford.edu/challenge/'},
  {name:'Real-robot evaluation & causal diagnosis',layer:'Evaluation',maturity:'Production',signal:'Blind trials · paired comparisons · hardware state',must:'Real trials expose latency, wear, calibration drift and environmental tails. Useful evaluation localizes failure rather than producing one celebratory number.',stack:'RoboArena · fixed workcells · shadow evaluation',owner:'Blind model identity where possible and record environmental, hardware and reset state.',mistake:'Changing prompts, gains or starting states between candidate policies.',source:'RoboArena',url:'https://robo-arena.github.io/'},

  {name:'Industrial robot safety standards',layer:'Safety',maturity:'Governance',signal:'Hazards · protective measures · validation',must:'ISO 10218-1:2025 and -2:2025 cover industrial robots and applications; collaborative operation adds ISO/TS 15066 considerations. Standards define engineered responsibilities, not model benchmarks.',stack:'Risk assessment · safeguarding · safety-rated controls',owner:'Map the deployed application and jurisdiction to applicable standards with qualified safety experts.',mistake:'Claiming “AI safety” or a force limit substitutes for system-level risk assessment.',source:'ISO robotics standards',url:'https://www.iso.org/cms/live/live/en/sites/isoorg/home/sectors/engineering/robotics.html'},
  {name:'US integration, LOTO & machine guarding',layer:'Safety',maturity:'Governance',signal:'Teach · setup · maintenance · abnormal modes',must:'Many robot incidents occur outside automatic production—during setup, testing and maintenance. In the US, general OSHA guarding and lockout/tagout duties apply even without one robot-specific OSHA standard.',stack:'ANSI/A3 R15.06-2025 · OSHA controls · procedures',owner:'Design safe states and access controls for every lifecycle mode, including recovery and data collection.',mistake:'Validating only autonomous operation while ignoring technicians and teleoperators in the cell.',source:'OSHA robotics overview',url:'https://www.osha.gov/robotics'},
  {name:'Runtime assurance & data governance',layer:'Safety',maturity:'Frontier',signal:'Monitors · envelopes · audit · privacy · rollback',must:'Learned policies need independent limits, health monitoring and traceable releases. Human video and home robotics also carry identity, consent and retention risk.',stack:'Safety PLC · constraint filters · signed artifacts · incident logs',owner:'Give each model/data release an owner, evaluation gate, rollback path and incident linkage.',mistake:'Relying on the learned policy to detect and constrain its own hazardous behavior.',source:'NIST AI Risk Management Framework',url:'https://www.nist.gov/itl/ai-risk-management-framework'},
  {name:'Robot cybersecurity & remote access',layer:'Safety',maturity:'Governance',signal:'Identity · least privilege · signed update · audit',must:'Teleoperation, fleet APIs and OTA turn a physical system into a security boundary. Authentication, encrypted transport, key rotation and safe offline behavior are part of physical risk.',stack:'SROS2 / DDS-Security · device identity · RBAC',owner:'Threat-model robot, operator, cloud and supplier paths; log privileged control and rehearse credential revocation.',mistake:'Exposing ROS graphs or remote expert tools as trusted internal plumbing.',source:'ROS 2 DDS-Security',url:'https://design.ros2.org/articles/ros2_dds_security.html'},

  {name:'Real-time inference & deployment graph',layer:'Operations',maturity:'Production',signal:'Sensor age → preprocessing → inference → command',must:'The deployed system is a timed graph across cameras, GPUs, networks and controllers. Throughput, tail latency and dropped observations change behavior.',stack:'ROS 2 QoS · TensorRT · edge compute · async inference',owner:'Trace p50/p95/p99 end-to-end latency and observation age under production load.',mistake:'Quoting accelerator kernel FPS as the robot control rate.',source:'ROS 2 quality of service',url:'https://docs.ros.org/en/jazzy/Concepts/Intermediate/About-Quality-of-Service-Settings.html'},
  {name:'Fleet telemetry, releases & observability',layer:'Operations',maturity:'Production',signal:'Health · events · versions · traces · remote assist',must:'A fleet needs comparable logs, model/config lineage, staged rollout, rollback and incident replay. Aggregate success alone cannot explain regressions.',stack:'Structured events · bags · feature flags · canary fleets',owner:'Make every episode reproducible from robot, model, calibration, asset and environment versions.',mistake:'Capturing video but not the synchronized decisions and system health that produced an incident.',source:'ROS 2 rosbag2',url:'https://github.com/ros2/rosbag2'},
  {name:'Multi-fleet & facility interoperability',layer:'Operations',maturity:'Production',signal:'Dispatch · traffic · doors · lifts · WMS/WES/MES',must:'Robots share facilities with other fleets and building systems. Interoperability spans task semantics and resource negotiation; a common position message is not a common mission contract.',stack:'Open-RMF · VDA 5050 · OPC UA · fleet adapters',owner:'Assign authority and incident responsibility across fleet manager, facility and robot vendors.',mistake:'Assuming an interoperability protocol covers navigation, safety and cross-vendor recovery.',source:'Open-RMF',url:'https://www.open-rmf.org/'},
  {name:'Reliability, throughput & unit economics',layer:'Operations',maturity:'Production',signal:'MTBF · intervention · cycle time · cost/success',must:'A robot product wins on useful work per hour under real staffing, maintenance and failure costs. Task success is one factor in a multiplicative system.',stack:'OEE · service logs · queueing · labor model',owner:'Track cost per successful task and autonomous useful-work time, not demo duration.',mistake:'Optimizing model accuracy while resets, teleop, charging or maintenance dominate economics.',source:'NIST robot performance metrics',url:'https://www.nist.gov/programs-projects/robotic-systems-smart-manufacturing-program'},
  {name:'Data flywheel & post-deployment learning',layer:'Operations',maturity:'Frontier',signal:'Observe → triage → label → train → gate → deploy',must:'Fleet data becomes leverage only when failures are discoverable, rights are clear and new policies pass stable regression gates.',stack:'Active learning · hard-negative mining · shadow mode · replay',owner:'Prioritize by expected product impact, novelty and safety—not upload volume.',mistake:'Training continuously on fleet logs without frozen tests, lineage or distribution controls.',source:'DROID dataset',url:'https://droid-dataset.github.io/'},
];

const maturityNotes:Record<Maturity,string>={
  Foundation:'Non-negotiable robotics literacy; stable concepts even when tools change.',
  Production:'Commonly deployed engineering with hard integration and reliability work.',
  Frontier:'Fast-moving research with promising evidence but unsettled interfaces or transfer.',
  Governance:'Contracts, standards and operating discipline that make claims auditable.',
};

const readiness=[
  ['Body + sensing','Frames, limits, clocks and calibration are versioned','Drift alarms; uncertainty exposed','Hidden controller or uncalibrated sensor'],
  ['Data','Schema, provenance and quality gates exist','Failure/intervention yield measured','Hours are the only KPI'],
  ['Model','Latency and action contract are measured','Frozen tests across task and embodiment slices','Cross-benchmark headline ranking'],
  ['Agency','Task state, verification and escalation are explicit','Disturbance + recovery trials','Success only from curated starts'],
  ['Safety','Lifecycle risk assessment and independent limits','Validation evidence tied to release','Policy is its own safety monitor'],
  ['Operations','Traceable release, canary and rollback','Cost/success, MTBF, intervention tracked','Demo success substitutes for SLOs'],
];

export default function Robotics2026Page(){
  const [layer,setLayer]=useState<'All'|Layer>('All');
  const [maturity,setMaturity]=useState<'All'|Maturity>('All');
  const [query,setQuery]=useState('');
  const [active,setActive]=useState(topics[0]);
  const visible=useMemo(()=>topics.filter(t=>(layer==='All'||t.layer===layer)&&(maturity==='All'||t.maturity===maturity)&&(!query||Object.values(t).flat().join(' ').toLowerCase().includes(query.toLowerCase()))),[layer,maturity,query]);
  const counts=Object.fromEntries(layerMeta.map(l=>[l.name,topics.filter(t=>t.layer===l.name).length]));
  return <main className="guide-page" id="top">
    <header className="training-topbar"><Link className="brand" href="/"><span>EØ</span>EGØ INDEX</Link><nav aria-label="Field guide navigation"><Link href="/robotics-2026" aria-current="page">Guide</Link><Link href="/real2sim">Real2Sim</Link><Link href="/model-architectures">Models</Link><Link href="/training-strategies">Training</Link><Link href="/#matrix">Data</Link></nav><a className="edition" href="#sources"><i/>Owner map · 2026</a></header>

    <section className="guide-hero">
      <div><p className="eyebrow">THE ROBOTICS SYSTEM, NOT ONLY THE MODEL</p><h1>WHAT YOU MUST<br/>KNOW IN <em>2026.</em></h1><p className="guide-lede">A field guide for building, buying or governing a robot product—from coordinate frames and contact to foundation policies, runtime assurance and fleet economics.</p><div className="hero-actions"><a className="primary" href="#stack">Explore the stack ↘</a><a href="#readiness">Audit a program</a></div></div>
      <aside><p>THE OWNER EQUATION</p><strong>CAPABILITY</strong><i>=</i><span>body × sensing × control × data × policy × agency</span><i>bounded by</i><strong>safety × reliability × economics</strong><small>A zero in any production layer can dominate model quality.</small></aside>
      <footer>{[['10','system layers'],[String(topics.length),'owner topics'],['4','maturity states'],['1','evidence contract']].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</footer>
    </section>

    <section className="guide-thesis">
      <div><p className="eyebrow">00 / SYSTEM THESIS</p><h2>ROBOTICS IS AN<br/><span>INTERFACE DISCIPLINE.</span></h2></div>
      <div>{[
        ['THE BODY SETS THE PRIOR','Reach, compliance, sensing and the controller determine which behavior is learnable and safe.'],
        ['DATA SETS THE SUPPORT','A model cannot recover states, contacts or failures that the capture pipeline systematically omits.'],
        ['AGENCY LIVES ABOVE REFLEX','Long workflows need task state, memory, verification, replanning and escalation—not merely longer action chunks.'],
        ['PRODUCTION CLOSES THE LOOP','A release is only real when latency, safety, reliability, labor and cost per successful task are governed.'],
      ].map((x,i)=><article key={x[0]}><b>0{i+1}</b><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div>
    </section>

    <section className="guide-stack" id="stack">
      <div className="section-heading"><div><p className="eyebrow">01 / THE OPERATING STACK</p><h2>FOLLOW THE<br/>DEPENDENCIES.</h2></div><p className="section-note">Click a layer to filter the registry. The stack runs both ways: intent flows down to actuation; measured state and evidence flow back up.</p></div>
      <div className="guide-stack-map">
        <aside><span>GOALS</span><i>↓</i><b>COMMAND<br/>FLOW</b></aside>
        <div>{[...layerMeta].reverse().map(l=><button key={l.name} onClick={()=>setLayer(layer===l.name?'All':l.name)} className={layer===l.name?'active':''} style={{'--layer-color':l.color} as React.CSSProperties}><span>{l.code}</span><strong>{l.name}</strong><p>{l.purpose}</p><b>{counts[l.name]} topics</b><i>{l.question}</i></button>)}</div>
        <aside><span>WORLD</span><i>↑</i><b>STATE +<br/>EVIDENCE</b></aside>
      </div>
      <div className="guide-interfaces">{[['BODY ↔ DATA','Action spaces, rates, frames and limits must be explicit.'],['SIM ↔ REAL','Validate the failure-relevant physics, not visual resemblance.'],['POLICY ↔ AGENCY','Define who owns state, termination, recovery and escalation.'],['MODEL ↔ OPS','Latency, lineage, rollback and telemetry are product interfaces.']].map(x=><article key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></article>)}</div>
    </section>

    <section className="guide-registry">
      <div className="section-heading"><div><p className="eyebrow">02 / OWNER REGISTRY</p><h2>QUERY THE<br/>FIELD.</h2></div><p className="section-note">The “mistake” field is deliberate: platform ownership is often the work of preventing silent interface errors.</p></div>
      <div className="guide-controls"><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search clocks, tactile, VLA, safety, fleet…"/></label><select value={layer} onChange={e=>setLayer(e.target.value as 'All'|Layer)}><option>All</option>{layerMeta.map(l=><option key={l.name}>{l.name}</option>)}</select><div>{(['All','Foundation','Production','Frontier','Governance'] as const).map(m=><button key={m} onClick={()=>setMaturity(m)} className={maturity===m?'active':''}>{m}</button>)}</div></div>
      <div className="guide-registry-grid"><div className="guide-topic-list"><header><b>{visible.length}</b><span>topics in current view</span><button onClick={()=>{setLayer('All');setMaturity('All');setQuery('')}}>Reset filters</button></header>{visible.map((t,i)=><button key={t.name} className={active.name===t.name?'active':''} onClick={()=>setActive(t)}><span>{String(i+1).padStart(2,'0')}</span><div><b>{t.name}</b><small>{t.layer} · {t.maturity}</small></div><i>→</i></button>)}</div>
        <article className="guide-topic-detail"><header><span>{active.layer}</span><b>{active.maturity}</b></header><h3>{active.name}</h3><p className="guide-signal">{active.signal}</p><p className="guide-must">{active.must}</p><dl><dt>REPRESENTATIVE STACK</dt><dd>{active.stack}</dd><dt>OWNER DECISION</dt><dd>{active.owner}</dd><dt>COMMON FAILURE</dt><dd>{active.mistake}</dd></dl><footer><a href={active.url} target={active.url.startsWith('/')?'_self':'_blank'} rel="noreferrer">{active.source} ↗</a>{active.links?.map(l=><a key={l.name} href={l.href}>{l.name} →</a>)}</footer></article>
      </div>
    </section>

    <section className="guide-maturity">
      <div className="section-heading"><div><p className="eyebrow">03 / 2026 MATURITY MAP</p><h2>STABLE CORE.<br/>MOVING EDGE.</h2></div><p className="section-note">“Frontier” does not mean unimportant; it means the evidence, interface or production recipe is still changing quickly.</p></div>
      <div>{(Object.entries(maturityNotes) as [Maturity,string][]).map(([m,n])=><article key={m}><header><span>{m}</span><b>{topics.filter(t=>t.maturity===m).length}</b></header><p>{n}</p><ul>{topics.filter(t=>t.maturity===m).slice(0,6).map(t=><li key={t.name}>{t.name}</li>)}</ul><button onClick={()=>{setMaturity(m);document.querySelector('.guide-registry')?.scrollIntoView()}}>Filter registry →</button></article>)}</div>
    </section>

    <section className="guide-readiness" id="readiness">
      <div className="section-heading"><div><p className="eyebrow">04 / PROGRAM READINESS</p><h2>AUDIT THE<br/>WHOLE PRODUCT.</h2></div><p className="section-note">This is an operating review, not a certification. A defensible program can point to artifacts, measurements and accountable owners.</p></div>
      <div className="guide-readiness-head"><span>Surface</span><span>Minimum contract</span><span>Production evidence</span><span>Red flag</span></div>{readiness.map((r,i)=><article key={r[0]}><span><b>{String(i+1).padStart(2,'0')}</b>{r[0]}</span><span>{r[1]}</span><span>{r[2]}</span><span>{r[3]}</span></article>)}
      <div className="guide-scorecard"><header><b>THE SIX NUMBERS A ROBOTICS OWNER SHOULD SEE WEEKLY</b><span>Disaggregate by task, site, hardware and release</span></header>{[['01','Autonomous useful-work time','Hours completing intended work without hands-on support'],['02','Task success + progress','Outcome and partial completion under a frozen protocol'],['03','Interventions / task-hour','Human rescue burden, reason and handling time'],['04','Recovery rate','Failures detected and resolved without reset or escalation'],['05','p95 cycle + decision latency','Tail behavior, including stale observations and queueing'],['06','Cost per successful task','Compute + labor + reset + service + depreciation']].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><p>{x[2]}</p></article>)}</div>
    </section>

    <section className="guide-production" id="production-proof">
      <div className="section-heading"><div><p className="eyebrow">05 / PRODUCTION PROOF</p><h2>NAME THE<br/>EVIDENCE TYPE.</h2></div><p className="section-note">A demo, a shipped component, a site field evaluation and multi-site autonomous uptime answer different questions. “Not disclosed” is data—not a zero.</p></div>
      <div className="guide-proof-ladder">{[
        ['A','LIVE OUTCOME','Measured work in an operating customer process','Digit: 100k+ totes; OTTO: 16M+ platform hours; Stretch: named warehouse deployments','Still ask for task denominator, assists, availability and MTTR'],
        ['B','NAMED DEPLOYMENT','Robot operating with a named partner or site','Apollo 2 partner fleets; Figure customer/fleet infrastructure evidence','A pilot or internal fleet is not a normalized production KPI'],
        ['C','SHIPPED SYSTEM','Generally available hardware, software or documented interface','Industrial arms, Jetson Thor, sensors, fleet middleware','Shipping proves availability—not autonomous task reliability'],
        ['D','ANNOUNCED / EARLY','Preorder, early access or future intended product','Home humanoid early access; next-generation production targets','Design targets and scheduled human assistance remain explicit'],
        ['R','REPRODUCIBLE REF.','Open workflow, code, weights or research benchmark','LeRobot, Isaac Lab, OpenVLA, public harnesses','Reproducibility is not commercial deployment evidence'],
      ].map(x=><article key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><p>{x[2]}</p></div><strong>{x[3]}</strong><small>{x[4]}</small></article>)}</div>
      <div className="guide-commercial-snapshot"><header><b>2026 COMMERCIAL SNAPSHOT</b><span>Vendor-reported unless a formal standard/certificate is named</span><Link href="/#production">Full company pipeline comparison →</Link></header>{[
        ['Task-specific baseline','ABB / UR / OTTO / Stretch','Strongest operational comparators','Installed cost · normalized uptime · interventions'],
        ['Commercial humanoid','Agility Digit + Arc','Published customer operation and work count','Fleet/site denominator · assists · MTTR · RaaS SLA'],
        ['Factory + fleet stack','Figure 03','Unusually detailed build, EOL and release infrastructure','Customer uptime · intervention rate · full safety status'],
        ['Pilot / data platform','Apptronik Apollo 2','Named Robot Park and partner data work','Hours · autonomous/teleop split · acceptance yield'],
        ['Human-assisted early access','1X NEO','Explicit scheduled remote Expert Mode','Assist frequency · staffing ratio · session privacy'],
      ].map(x=><article key={x[0]}><span><b>{x[0]}</b><small>{x[1]}</small></span><span>{x[2]}</span><span><i>NOT DISCLOSED</i>{x[3]}</span></article>)}</div>
      <div className="guide-roles"><header><b>OPERATOR CURRICULUM</b><span>Role clarity is production infrastructure</span></header>{[
        ['01','SITE / PROCESS','Task, takt, exception taxonomy, acceptance and TCO'],['02','CAPTURE / TELEOP','Calibration, nominal + recovery demos, consent and QC'],['03','FLOOR OPERATOR','Preflight, missions, alarms, safe pause and escalation'],['04','FLEET / REMOTE ASSIST','Dispatch, assist triage, handback, canary and rollback'],['05','MAINTENANCE','LOTO, stored energy, replacement, calibration and return-to-service'],['06','SAFETY / INTEGRATION','Risk route, safeguarding, validation and management of change'],['07','ML / DATA OWNER','Lineage, isolation, failure mining, gates and replay evidence'],['08','SECURITY / INCIDENT','Identity, retention, incident hold, CAPA and recurrence test'],
      ].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><p>{x[2]}</p></article>)}</div>
    </section>

    <section className="guide-safety">
      <div><p className="eyebrow">06 / SAFETY & ASSURANCE</p><h2>THE MODEL IS<br/>NOT THE SAFETY CASE.</h2><p>Applicable requirements depend on robot type, application and jurisdiction. The durable pattern is system risk assessment, independent protective measures, validation and lifecycle control.</p></div>
      <div className="guide-safety-flow">{[['01','IDENTIFY','People, modes, hazards, foreseeable misuse'],['02','REDUCE','Inherently safe design and engineered safeguards'],['03','VALIDATE','Limits, stopping, access, faults and abnormal modes'],['04','OPERATE','Training, maintenance, incidents, change control'],['05','RE-ASSESS','New model, tool, site, task or workflow']].map((x,i)=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><p>{x[2]}</p>{i<4&&<i>→</i>}</article>)}</div>
      <footer><a href="https://www.iso.org/cms/live/live/en/sites/isoorg/home/sectors/engineering/robotics.html" target="_blank" rel="noreferrer"><b>ISO 10218-1/-2:2025</b><span>Industrial robot and application safety ↗</span></a><a href="https://www.automate.org/robotics/safety/robot-safety-standard-documents" target="_blank" rel="noreferrer"><b>ANSI/A3 R15.06-2025</b><span>US industrial robot safety documents ↗</span></a><a href="https://www.osha.gov/robotics" target="_blank" rel="noreferrer"><b>OSHA ROBOTICS</b><span>US hazards and applicable standards ↗</span></a><a href="https://www.iso.org/standard/62996.html" target="_blank" rel="noreferrer"><b>ISO/TS 15066</b><span>Collaborative robot guidance ↗</span></a></footer>
    </section>

    <section className="guide-pathways">
      <div className="section-heading"><div><p className="eyebrow">07 / DEEP WORKBENCHES</p><h2>GO FROM MAP<br/>TO EVIDENCE.</h2></div><p className="section-note">The field guide is the index. These workbenches carry the datasets, native visuals, comparisons, model details and evidence ledgers.</p></div>
      <div>{[
        ['DATA + CAPABILITY','Egocentric, robot, teleop, rollout and tactile data mapped to task agency and horizon.','Explore the main atlas','/'],
        ['REAL2SIM','Reconstruction, 4D tracking, physics, digital twins, replay and transfer evidence.','Open the workbench','/real2sim'],
        ['POLICY ARCHITECTURES','Encoders, backbones, action heads, embodiments, public benchmarks and queryable scores.','Inspect models','/model-architectures'],
        ['TRAINING STRATEGIES','Pretraining vs post-training data, recipes, long-horizon adaptation and a concrete barista plan.','Compare strategies','/training-strategies'],
      ].map((x,i)=><Link key={x[0]} href={x[3]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p><b>{x[2]} →</b></Link>)}</div>
    </section>

    <section className="guide-sources" id="sources"><div><p className="eyebrow">08 / EVIDENCE POLICY</p><h2>A LIVING MAP,<br/>WITH GUARDRAILS.</h2></div><div><p><b>Primary before promotional.</b> Architecture, numbers and claims link to official project pages, documentation, standards bodies or publisher artifacts.</p><p><b>Protocol before rank.</b> Scores remain attached to embodiment, task set, observations, resets, trials and date. Cross-protocol sorting is not a leaderboard.</p><p><b>Unknown stays unknown.</b> Undisclosed data, parameters, action spaces and deployment details are not inferred from demos.</p><p><b>Frontier is time-stamped.</b> Fast-moving model and company claims are treated as snapshots, not permanent facts.</p></div></section>
  </main>;
}
