'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';

type Input = 'Human exo'|'Human ego'|'Robot rollout'|'Site scan'|'RGB-D'|'Single image';
type Output = 'Manipulation'|'Humanoid'|'Environment'|'Evaluation';
type Access = 'Open'|'Partial'|'Closed';
type Method = {
  name:string; year:number; org:string; inputs:Input[]; output:Output; access:Access; url:string;
  capture:string; recover:string[]; representation:string; sim:string; transfer:string; metric:string; limit:string;
  automation:number; physics:number; stages:number[];
};

const methods:Method[] = [
  {name:'ROSE',year:2025,org:'Georgia Tech · UC Berkeley',inputs:['Human exo'],output:'Manipulation',access:'Open',url:'https://rose-project-2025.github.io/',capture:'Casual monocular human video; equipment-agnostic.',recover:['metric scene','object mesh','SE(3) object trajectory','gravity'],representation:'Gravity-aligned scene/object meshes plus object motion in one metric frame.',sim:'Simulator assets for motion planning or two-stage RL.',transfer:'11/13 real trials succeeded; reported simulated average 0.90 for two-stage RL.',metric:'~8× faster reconstruction than improved Video2Policy; average rotation RPE 4.866°.',limit:'Rigid tabletop objects; reconstructed trajectory is a task prior, not a robot action label.',automation:5,physics:2,stages:[1,2,3,5,6]},
  {name:'EgoEngine',year:2026,org:'Georgia Tech',inputs:['Human ego','RGB-D'],output:'Manipulation',access:'Partial',url:'https://egoengine.github.io/',capture:'Aria Gen2 ego video with depth and 3D hand keypoints.',recover:['object mesh','6D object path','3D hands','robot-view video','executable dexterous motion'],representation:'Digital twin plus retargeted robot trajectory and occlusion-aware robot-in-ego rendering.',sim:'Solver escalation: replay → MPC → residual RL, optimized against object motion.',transfer:'Zero-real-demo policies across four tasks; generated-action SR 0.90 on Aria input.',metric:'200 input videos; policy SR 0.40 / 0.35 / 0.70 / 0.60 by task.',limit:'Depends on Aria depth/hands, known object mesh and calibrated setup; reported generation is only 2.88 demos/hour on RTX 4090.',automation:4,physics:4,stages:[1,2,3,4,5,6]},
  {name:'X-Sim',year:2025,org:'Cornell',inputs:['Human exo','RGB-D','Site scan'],output:'Manipulation',access:'Open',url:'https://portal.cs.cornell.edu/X-Sim/',capture:'RGB-D human demonstration plus a phone scan of the scene.',recover:['2D Gaussian scene','object trajectory','dense object-centric reward'],representation:'Photorealistic scene and embodiment-independent reward rather than direct hand retargeting.',sim:'Privileged RL discovers robot behavior; synthetic rollouts vary view, light and state.',transfer:'Image diffusion policy deployed across five real tasks.',metric:'+30% task progress; matches behavior cloning with 10× less collection time.',limit:'Needs object tracking, RGB-D and online action replay/calibration; object reward does not identify general contact semantics.',automation:3,physics:3,stages:[1,2,3,5,6]},
  {name:'Video2Sim2Real',year:2026,org:'Georgia Tech',inputs:['Human exo'],output:'Manipulation',access:'Open',url:'https://video2sim2real.github.io/',capture:'A single human manipulation video.',recover:['digital twin','object keyframes','hand/object motion','collision constraints'],representation:'Simulator-ready twin plus object-centric anchors used to repair robot retargeting.',sim:'Imitation learning for perception robustness + residual RL for finger contact.',transfer:'Collision-aware planning and dexterous real-robot deployment across everyday tasks.',metric:'Improves simulated success, safety and trajectory coherence over reported baselines.',limit:'Single demonstrations still depend on off-the-shelf reconstruction and task-specific asset validity.',automation:5,physics:4,stages:[1,2,3,4,5,6]},
  {name:'Human2Sim2Robot',year:2025,org:'Stanford',inputs:['RGB-D','Human exo'],output:'Manipulation',access:'Open',url:'https://human2sim2robot.github.io/',capture:'One RGB-D human demonstration; no glove or teleoperation.',recover:['object pose path','pre-grasp hand pose','object geometry'],representation:'Embodiment-agnostic object trajectory reward plus exploration initialization.',sim:'Dexterous-hand RL crosses the human/robot morphology gap.',transfer:'Grasping, non-prehensile and multi-step tasks on a real dexterous hand.',metric:'+55% over object-aware open-loop replay; +68% over augmented imitation learning.',limit:'Requires RGB-D and an object model; a reward distilled from one path may under-specify alternatives.',automation:4,physics:4,stages:[1,2,3,4,5,6]},
  {name:'VideoManip',year:2026,org:'Shanghai AI Lab · collaborators',inputs:['Human exo'],output:'Manipulation',access:'Partial',url:'https://videomanip.github.io/',capture:'Monocular in-scene or in-the-wild human RGB video.',recover:['3D hand path','object mesh/scale','6D object motion','contact-optimized grasp'],representation:'Explicit hand/object trajectories retargeted to a dexterous robot.',sim:'Contact optimization and interaction-centric grasp model synthesize robot trajectories.',transfer:'LEAP Hand real deployment across seven tasks.',metric:'70.25% sim grasp success · 62.86% real average, +15.87 pp over retargeting.',limit:'Trajectory-to-policy pipeline, not a complete scene/dynamics twin; in-scene use assumes known camera–robot extrinsics.',automation:4,physics:3,stages:[1,2,3,4,5,6]},
  {name:'Real2Render2Real',year:2025,org:'UC Berkeley · TRI',inputs:['Human exo','Site scan'],output:'Manipulation',access:'Open',url:'https://real2render2real.com/',capture:'Smartphone object scans and one monocular human demonstration.',recover:['3D objects','6D part motion','robot IK','rendered observations/actions'],representation:'Robot training pairs rendered from object-centric trajectories across embodiments.',sim:'Rendering pipeline deliberately disables collision physics.',transfer:'π0-FAST and Diffusion Policy tested over 1,050 physical trials.',metric:'Competitive final performance at 1/27 generation time.',limit:'A useful negative control: rendering, not simulation—no mass, friction, contact or counterfactual dynamics.',automation:5,physics:1,stages:[1,2,3,6]},
  {name:'VideoMimic',year:2025,org:'UC Berkeley',inputs:['Human exo'],output:'Humanoid',access:'Open',url:'https://www.videomimic.net/',capture:'123 casual or internet monocular RGB videos.',recover:['metric 4D human','scene point cloud','gravity','retargeted robot motion'],representation:'Human trajectory + meshed environment + local height map.',sim:'DeepMimic-style RL, domain randomization and DAgger distillation.',transfer:'One Unitree G1 policy for stairs, terrain, sitting and standing.',metric:'Real-robot contextual control; reconstruction and policy code released.',limit:'Whole-body contact is environment-level; it does not recover fine hand-object manipulation.',automation:4,physics:3,stages:[1,2,3,4,5,6]},
  {name:'HA-HOI',year:2026,org:'HKUST · collaborators',inputs:['Human exo'],output:'Humanoid',access:'Partial',url:'https://knoxzhao.github.io/real2sim_in_HOI/',capture:'In-the-wild monocular human-object interaction video.',recover:['4D human','object alignment','contact relation','teacher motion'],representation:'Human-first, object-follow 4D animation projected into physics.',sim:'Physics-based humanoid-object rollout tracks the reconstructed teacher.',transfer:'Simulation-ready HOI animation; physical robot transfer is not the main demonstrated endpoint.',metric:'Reported gains in alignment, contact consistency and temporal stability.',limit:'Visually plausible contact can still be functionally wrong; real-robot evidence remains limited.',automation:4,physics:4,stages:[1,2,3,4,5]},
  {name:'RialTo',year:2024,org:'MIT · UW',inputs:['Site scan','Robot rollout'],output:'Manipulation',access:'Open',url:'https://real-to-sim-to-real.github.io/RialTo/',capture:'Phone scans of the target scene and small real robot demonstration sets.',recover:['scene mesh','object assets','robot demo alignment'],representation:'Editable digital twin plus demonstrations transferred by inverse distillation.',sim:'RL robustification under pose, disturbance and visual variation.',transfer:'Teacher-student distillation combines sim policy with real demonstrations.',metric:'Publisher reports >67% increase in policy robustness across eight tasks.',limit:'GUI-assisted scene construction and asset cleanup are not fully automatic.',automation:3,physics:3,stages:[1,2,3,5,6]},
  {name:'SimFoundry',year:2026,org:'NVIDIA GEAR',inputs:['Site scan'],output:'Environment',access:'Partial',url:'https://research.nvidia.com/labs/gear/simfoundry/',capture:'One video of a real scene.',recover:['instances','depth','3D assets','physical attributes','scene graph'],representation:'Interactive digital twin plus generated digital cousins.',sim:'Compiled and sanity-checked in a physics simulator for policy training/evaluation.',transfer:'Reported manipulation transfer from twin and cousin distributions.',metric:'Sim/real policy success correlation r=0.911; π0.5-DROID co-training 28→46% on 13 tasks.',limit:'Generated assets preserve affordance imperfectly; articulation and material estimates need validation.',automation:5,physics:3,stages:[1,2,3,4,5,6]},
  {name:'Digital Cousins / ACDC',year:2024,org:'Stanford · Columbia · Toyota Research',inputs:['Single image'],output:'Environment',access:'Open',url:'https://digital-cousins.github.io/',capture:'A single RGB image of a target scene.',recover:['instances','layout','nearest 3D assets','affordance similarity'],representation:'A distribution of semantically and geometrically similar interactive scenes, not an exact twin.',sim:'Policies train across cousin scenes to favor generalization.',transfer:'Zero-shot deployment into the original physical scene.',metric:'Reported 90% vs 25% zero-shot success for cousin- vs twin-trained policies.',limit:'Similarity is not physical identity; wrong joints, clearances or collision shapes remain possible.',automation:5,physics:2,stages:[1,2,3,5,6]},
  {name:'Scalable Real2Sim',year:2025,org:'MIT · Amazon Robotics',inputs:['Robot rollout'],output:'Environment',access:'Open',url:'https://scalable-real2sim.github.io/',capture:'Autonomous pick/place with an external camera and joint torque sensing.',recover:['visual mesh','collision mesh','mass/inertia','object-centric assets'],representation:'Physics-aware object asset with measured visual and inertial properties.',sim:'Assets are validated by reproducing object dynamics.',transfer:'Designed for scalable manipulation asset creation and system identification.',metric:'39-minute fully autonomous collection demonstration.',limit:'Robot interaction is more expensive than passive video and focuses on pickable rigid objects.',automation:5,physics:5,stages:[1,2,3,4,5]},
  {name:'URDFormer',year:2024,org:'Stanford · Columbia · TRI',inputs:['Single image'],output:'Environment',access:'Open',url:'https://urdformer.github.io/',capture:'One RGB or internet image of an articulated scene/object.',recover:['part boxes','parent tree','joint type/axis','matched part meshes'],representation:'URDF articulation assembled from a predefined mesh library.',sim:'Interactive cabinets/appliances used in Reality Gym.',transfer:'Real UR5 and Stretch demonstrations for open, close, fetch and collect.',metric:'Fine-tuning adds 13 F1 points; model soup adds >10 more.',limit:'Does not predict mass, friction or other physics; mesh-library and part-detection errors constrain fidelity.',automation:5,physics:2,stages:[1,2,3,5,6]},
  {name:'NVIDIA NuRec 26.04',year:2026,org:'NVIDIA',inputs:['Site scan'],output:'Environment',access:'Partial',url:'https://docs.nvidia.com/nurec/',capture:'Mono/stereo video; broader NCore accepts camera, LiDAR, radar, poses and depth.',recover:['camera poses','stereo depth','mesh/occupancy','3D Gaussian scene','tracks'],representation:'USDZ with USD scene, neural checkpoint, camera rig trajectories and sequence tracks.',sim:'NuRec volume loads in Isaac Sim/Omniverse; a mesh supplies collisions.',transfer:'Official robotics workflow and PhysicalAI reconstruction dataset for navigation/training/testing.',metric:'Production container and documented mono/stereo pipelines.',limit:'Static environment reconstruction: visual geometry has no inherent physics, articulation or interaction state.',automation:5,physics:2,stages:[1,2,3,5]},
  {name:'Lightwheel × Geely',year:2026,org:'Lightwheel · Geely · NVIDIA',inputs:['Human ego','Robot rollout'],output:'Environment',access:'Closed',url:'https://lightwheel.ai/media/geely-humanoid-robots',capture:'Operator ego RGB-D, gloves/wrist cameras plus separate physical measurement of equipment.',recover:['3D hand/body','semantic actions','tooling assets','friction/contact/dynamics'],representation:'Measured SimReady OpenUSD line twin, not video-only reconstruction.',sim:'Isaac Sim/Lab generates robot experience; GR00T N1.7 is fine-tuned in the twin.',transfer:'Humanoids demonstrated component transport, tray placement and dual-arm handling on a live auto line.',metric:'Vendor reports 10× shorter task cycle, 100:1 sim:real and 10× lower training cost.',limit:'Vendor case study: no public success rates, reconstruction benchmark, independent audit or downloadable twin.',automation:3,physics:5,stages:[1,2,3,4,5,6]},
  {name:'PhysTwin',year:2025,org:'Columbia · UIUC',inputs:['Human exo','RGB-D'],output:'Environment',access:'Open',url:'https://jianghanxiao.github.io/phystwin-web/',capture:'Sparse interaction videos of rope, cloth, plush and packages.',recover:['complete geometry','topology','dense physical properties','Gaussian appearance'],representation:'Object-specific spring–mass twin coupled to Gaussian appearance and real-time simulation.',sim:'Supports teleoperation, future prediction and model-based planning.',transfer:'Validated across 15 deformable interaction types; official code is public.',metric:'Reconstruction, rendering, tracking and future-prediction comparisons in paper.',limit:'Optimization-heavy object-specific acquisition; scaling to clutter and multiple interacting deformables is unproven.',automation:3,physics:5,stages:[1,2,3,4,5]},
  {name:'EgoPhys',year:2026,org:'Georgia Tech · collaborators',inputs:['Human ego'],output:'Manipulation',access:'Partial',url:'https://hjhyunjinkim.github.io/EgoPhys/',capture:'One ~7-second Project Aria egocentric human-play clip.',recover:['dense 4D points','spring-mass graph','stiffness parameters','hand-driven deformation'],representation:'Differentiable deformable-object twin with a learned per-spring stiffness codebook.',sim:'Twin is used as the forward model inside MPPI.',transfer:'Zero-fine-tune xArm6 lift/pull planning on physical deformables.',metric:'Reported Chamfer-distance reductions of 16%, 25% and 78% across tasks.',limit:'Only 19 sequences and 11 held-out tests; one deformable at a time, with hand as observed actuator and no tactile force.',automation:4,physics:5,stages:[1,2,3,4,5,6]},
  {name:'EMPM',year:2026,org:'Robotics and AI Institute · UCLA',inputs:['RGB-D','Robot rollout'],output:'Manipulation',access:'Partial',url:'https://embodied-mpm.github.io/',capture:'Multi-view RGB-D video, tracked 3D object shape and applied interaction; supports streaming sensory updates.',recover:['geometry','Gaussian appearance','MPM material parameters','online parameter updates'],representation:'Differentiable Material Point Method twin for rope, cloth, dough, plasticine and tearing behavior.',sim:'Optimizes continuum material dynamics offline or online and explores controller actions in the learned twin.',transfer:'Robot follows simulated rollouts for rope and bread-dough manipulation.',metric:'Publisher reports gains over PhysTwin spring–mass baselines on highly deformable interactions.',limit:'Not egocentric or passive-video scale; multi-view RGB-D and controlled feedback are stronger capture assumptions, and code is still listed as coming soon.',automation:3,physics:5,stages:[1,2,3,4,5,6]},
  {name:'Boba',year:2026,org:'UIUC · Columbia · Meta',inputs:['RGB-D'],output:'Environment',access:'Open',url:'https://jianxiapyh.github.io/Boba-project-page/',capture:'Consumes a reconstructed PhysTwin-style Gaussian physical twin rather than raw ego video directly.',recover:['shared twin template','batched dynamic state','surrogate spring–mass model'],representation:'Physics-based Gaussian digital twin redesigned for independent batched rollouts.',sim:'3,309.9 aggregate FPS on RTX 4090 reported; supports MPC and PPO for deformable objects.',transfer:'Accelerates rope and cloth model-predictive planning and simulation learning.',metric:'>10× single-instance speedup over PhysTwin; 16.2× aggregate throughput over optimized single-instance execution.',limit:'A simulation systems accelerator, not a better inverse-physics estimator; it inherits the source twin’s modeling errors.',automation:3,physics:5,stages:[3,4,5,6]},
  {name:'WANDA',year:2026,org:'Carnegie Mellon',inputs:['Robot rollout','RGB-D'],output:'Manipulation',access:'Partial',url:'https://wanda.lecar-lab.org/',capture:'One RGB-D teleoperated mobile-manipulator demonstration.',recover:['3DGS background','scene/object mesh','6D object pose','robot/object trajectories'],representation:'Interactive 4D world with reconstructed foreground, generated variants and replay.',sim:'Isaac foreground composited with splat; motion planning and Corrective State Expansion.',transfer:'π0.5/ACT across five long-horizon AgiBot G1 tasks; cross-embodiment Linearbot replay.',metric:'Real task progress 15.7→54.8%; one source hour costs ~3 GPU-hours.',limit:'Rigid/articulated objects only; cloth/fluids are replayed, not physically modeled; source is teleoperation, not passive human video.',automation:4,physics:3,stages:[1,2,3,4,5,6]},
  {name:'DreMa',year:2024,org:'TU Munich · collaborators',inputs:['Robot rollout'],output:'Manipulation',access:'Open',url:'https://dreamtomanipulate.github.io/',capture:'One real robot demonstration per task variation.',recover:['Gaussian scene','object composition','robot trajectory'],representation:'Composable 3D Gaussian world model coupled to physics.',sim:'Counterfactual “imagination” creates augmented imitation data.',transfer:'Real Franka policies learn novel tasks from one example per variation.',metric:'One-shot policy-learning evidence across real manipulation tasks.',limit:'Photorealistic rendering does not guarantee correct contact or dynamics.',automation:4,physics:3,stages:[1,2,3,5,6]},
  {name:'Real2Sim-Eval',year:2025,org:'Columbia · SceniX · Google DeepMind',inputs:['Site scan','Robot rollout'],output:'Evaluation',access:'Open',url:'https://real2sim-eval.github.io/',capture:'Workspace/object scans plus human-object and robot interaction videos.',recover:['3D Gaussian scene','PhysTwin soft-body asset','color transform','physical parameters'],representation:'Photorealistic renderer synchronized with a physics-optimized deformable twin.',sim:'Reproducible policy evaluation for packing, rope routing and pushing.',transfer:'Simulated improvements are checked against real execution patterns; artifacts and checkpoints are public.',metric:'Reports positive sim/real performance correlation across the three task families.',limit:'Manual initial-state matching remains in the loop; soft-body identification is task and material specific.',automation:3,physics:5,stages:[1,2,3,4,5]},
  {name:'Agentic Real2Sim',year:2026,org:'Columbia · Johns Hopkins · collaborators',inputs:['Robot rollout','Human exo'],output:'Environment',access:'Partial',url:'https://ericchen321.github.io/agentic_real2sim.github.io/',capture:'Recordings of object-robot, deformable and humanoid interaction.',recover:['geometry','object state','physics parameters','actors/cameras/trajectories'],representation:'A vision-language-agent assembled simulatable episodic twin.',sim:'Agents select tools, repair meshes, align frames and validate a runnable scene.',transfer:'Proposed for policy learning and evaluation across normally separate domains.',metric:'Open-weight VLM backend reported comparable conversion success at lower cost.',limit:'Agentic glue reduces labor but can silently propagate perception or tool errors.',automation:5,physics:4,stages:[1,2,3,4,5]},
  {name:'DISCOVERSE',year:2025,org:'Tsinghua · collaborators',inputs:['Site scan'],output:'Environment',access:'Open',url:'https://air-discoverse.github.io/',capture:'Reconstructed real scenes and robot/task assets.',recover:['3D Gaussian appearance','collision geometry','robot/task state'],representation:'Hybrid 3DGS rendering and physics simulation.',sim:'Unified modular simulator for photorealistic Real2Sim2Real.',transfer:'Reports zero-shot transfer on contact-rich manipulation.',metric:'Open simulator with native real/sim demonstrations.',limit:'Hybrid render/physics alignment is an engineering contract; a Gaussian scene alone cannot collide.',automation:3,physics:4,stages:[2,3,4,5,6]},
  {name:'Aria Digital Twin',year:2023,org:'Meta Reality Labs',inputs:['Human ego'],output:'Environment',access:'Open',url:'https://www.projectaria.com/datasets/adt/',capture:'Calibrated egocentric RGB, stereo SLAM, eye tracking and IMU in instrumented rooms.',recover:['device pose','semi-dense points','metric depth','object poses','eye gaze'],representation:'Time-aligned metric ground truth around egocentric activity.',sim:'A reconstruction/benchmark substrate, not a turnkey physics simulator.',transfer:'Useful for validating SLAM, pose, object tracking and ego-to-world grounding.',metric:'Sequence explorer exposes coverage, trajectory, depth and object interaction records.',limit:'Known-scene ground truth and rigid assets do not include full contact dynamics or robot actions.',automation:2,physics:1,stages:[1,2]},
];

const stageLabels = ['Capture + sync','Geometry + scale','Actors + trajectories','Physics + contact','Runnable simulation','Policy / evaluation'];
const nativeMedia = [
  {name:'ROSE',label:'human video → reconstructed twin → robot',src:'https://rose-project-2025.github.io/static/videos/teaser_video.mp4',url:'https://rose-project-2025.github.io/'},
  {name:'VideoMimic',label:'monocular video → 4D human/scene → G1',src:'https://www.videomimic.net/figs/videomimic_teaser.mp4',url:'https://www.videomimic.net/'},
  {name:'Human2Sim2Robot',label:'one RGB-D demo → dexterous sim-to-real',src:'https://human2sim2robot.github.io/static/videos/teaser.mov',url:'https://human2sim2robot.github.io/'},
  {name:'SimFoundry',label:'one scene video → interactive twin + cousins',src:'https://research.nvidia.com/labs/gear/simfoundry/videos/Simfoundry_Teaser.mp4',url:'https://research.nvidia.com/labs/gear/simfoundry/'},
];

const reconstructionSubstrates=[
  {name:'Aria Digital Twin',scale:'236 calibrated sequences',signals:'RGB · stereo SLAM · IMU · gaze · depth · 6D objects · skeletons · GLB assets',role:'Metric ego pose/object/occlusion ground truth; benchmark substrate, not physics.',url:'https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_digital_twin_dataset'},
  {name:'HOT3D',scale:'1.5M multiview frames · 3.7M+ images',signals:'Calibrated Aria/Quest · 3D hands · 6D objects · CAD models',role:'Direct benchmark for the hand/object tracker before contact and action recovery.',url:'https://facebookresearch.github.io/hot3d/'},
  {name:'Ego-Exo4D V2',scale:'1,286.3 video h · 5,035 takes',signals:'Synchronized ego + 4–5 exo · global cameras · body/hands · point clouds · keysteps',role:'Best multiview source for metric motion and procedure structure; not SimReady assets.',url:'https://docs.ego-exo4d-data.org/'},
  {name:'HOI4D',scale:'2.4M RGB-D frames · 4,000 sequences',signals:'3D hands · object pose · action · meshes · point clouds',role:'Category-level 4D interaction supervision; observation labels are not executable dynamics.',url:'https://hoi4d.github.io/'},
  {name:'Isaac Video to Data',scale:'Open v0.2 reconstruction stack',signals:'Ego MP4 → masks · metric depth · hand track · object mesh · smoothed 6D pose · QC videos',role:'A reproducible front-end for retargeting/Isaac; no policy or physics-ID benchmark yet.',url:'https://nvidia-isaac.github.io/video_to_data/reconstruction/'},
  {name:'Stera-10M',scale:'200 h · 354 sessions · 10M frames',signals:'iPhone RGB · LiDAR · IMU · ARKit 6DoF → hands/body · mesh · point cloud · depth',role:'Capture/geometry infrastructure; the launch says 3DGS and Real2Sim export are upcoming.',url:'https://www.fpvlabs.ai/essays/launching-stera'},
  {name:'Ropedia Xperience',scale:'30K h / 1,500 scenes claimed',signals:'Ego RGB · IMU · depth · pose → MANO · SLAM · object mesh · 3DGS · semantic layers',role:'Commercial data engine; no public simulator export, physics benchmark or policy transfer.',url:'https://ropedia.com/'},
  {name:'Digital Twin Catalog',scale:'2,000 scanned objects',signals:'DSLR + egocentric Aria · materials · poses · downloadable GLB',role:'High-quality static asset catalog; no interaction dynamics.',url:'https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/digital_twin_catalog/'},
];

const productionPipelines=[
  ['Lightwheel × Geely','ego RGB-D + measured tooling','SimReady OpenUSD · measured physics','Isaac Sim/Lab → GR00T N1.7','named live auto-line manipulation','Vendor metrics; no public twin','https://lightwheel.ai/media/geely-humanoid-robots'],
  ['NVIDIA NuRec','mono/stereo/LiDAR site capture','3DGS + mesh/occupancy · USDZ','Isaac Sim/Omniverse','production reconstruction substrate','static scene; user supplies physics','https://docs.nvidia.com/nurec/'],
  ['Niantic × Flexion','~5 min 360° walkthrough','metric 3DGS + aligned mesh · USDZ','Isaac Lab navigation training','zero-shot physical humanoid nav','navigation, not manipulation','https://www.nianticspatial.com/blog/flexion-humanoid-real2sim-sim2real'],
  ['FieldAI × NVIDIA','robot vision/depth/LiDAR streams','living NuRec digital twins','Isaac Sim/Lab validation','deployed industrial sites','manipulation is future/adjacent','https://www.fieldai.com/news/fieldai-and-nvidia-omniverse-building-the-next-generation-of-industrial-ai'],
  ['Dirac Robotics','single-camera walkthrough','geometry + claimed mass/inertia/friction/joints','USD · Isaac-ready','early commercial service','no public accuracy/transfer benchmark','https://www.diracrobotics.com/'],
  ['XGRIDS','LiDAR+RGB rig or video','large-scale 3DGS + optional mesh','USD/USDZ · Omniverse','commercial capture/export','no policy or physics-ID evidence','https://www.xgrids.com/portalcam'],
];

const gaps = [
  ['Geometry is not collision','NeRF/3DGS can render a scene beautifully while surfaces interpenetrate, thin parts disappear, and collision meshes remain unusable.'],
  ['Motion is not action','A wrist, hand or object trajectory omits force, impedance, grasp mode and the counterfactual choices needed by a different embodiment.'],
  ['Contact is under-observed','Monocular RGB rarely identifies pressure, friction, compliance or whether proximity is load-bearing contact.'],
  ['Dynamics are non-identifiable','Many mass/friction/damping combinations explain the same short clip. Active robot probing is often more informative than passive video.'],
  ['A twin can overfit','An exact replica narrows variation. Digital cousins and domain randomization may transfer better when deployment differs from the scan.'],
  ['Success can be mismeasured','Chamfer distance, SSIM and reprojection error do not guarantee task success; simulated success does not guarantee ranking preservation in reality.'],
];

type FormatRole='Runtime asset'|'Training data'|'Benchmark contract';
type SimFormat={name:string;role:FormatRole;files:string;home:string;purpose:string;carries:string;missing:string;owner:string;url:string};

const simFormats:SimFormat[]=[
  {name:'OpenUSD + UsdPhysics',role:'Runtime asset',files:'.usd · .usda · .usdc · packaged .usdz',home:'Isaac Sim · Omniverse · USD-native pipelines',purpose:'Layered scene graph for large worlds, variants, references, visual assets and baseline rigid-body physics.',carries:'Transforms and units; meshes/materials; rigid bodies; collision shapes; mass; joints/drives; articulations; physics materials.',missing:'Engine-specific extensions, controllers, sensors, deformable/contact fidelity and task logic may remain outside portable core schemas.',owner:'Keep authored source layers separate from generated cache; pin schema/runtime versions and asset dependencies.',url:'https://openusd.org/release/api/usd_physics_page_front.html'},
  {name:'MJCF',role:'Runtime asset',files:'.xml · compiled .mjb',home:'MuJoCo · MJX',purpose:'Native MuJoCo model language for compact, simulation-oriented dynamical systems and robot control.',carries:'Bodies/geoms/sites; joints/constraints; tendons; actuators; sensors; contact rules; assets; defaults and compiler settings.',missing:'Not a general production scene interchange; rendering/scene composition and engine-specific contact semantics do not round-trip losslessly.',owner:'Retain editable MJCF plus referenced meshes/textures; never treat a compiled MJB as the only source artifact.',url:'https://mujoco.readthedocs.io/en/latest/modeling.html'},
  {name:'URDF / Xacro + SRDF',role:'Runtime asset',files:'.urdf · .xacro · .srdf + mesh/config bundle',home:'ROS 2 · MoveIt · broad robot tooling',purpose:'Robot kinematic structure and geometry; Xacro parameterizes generation while SRDF adds planning semantics.',carries:'Links/joints; origins; visual and collision meshes; inertial parameters; limits; transmissions/extensions by ecosystem.',missing:'A URDF alone is not a world, task, sensor model or calibrated actuator/contact model; closed mechanisms and portable physics are limited.',owner:'Package the generated URDF, Xacro source, meshes, semantic/config files, ros2_control contract and exact tool-center frame.',url:'https://docs.ros.org/en/rolling/Tutorials/Intermediate/URDF/URDF-Main.html'},
  {name:'SDFormat',role:'Runtime asset',files:'.sdf + model/world resources',home:'Gazebo · Open Robotics simulation stack',purpose:'Versioned robot, object and full-world description for simulation.',carries:'Worlds/scenes; models/links/joints; physics; sensors; lights; collision/visual geometry; materials; actors and plugins.',missing:'Plugins and simulator behavior can reduce portability; SDF version and libsdformat release are separate compatibility constraints.',owner:'Pin both specification and parser/simulator versions; include every URI resource and plugin dependency.',url:'https://sdformat.org/spec/'},
  {name:'glTF / GLB',role:'Runtime asset',files:'.gltf + buffers/textures · .glb',home:'Web/graphics interchange · asset ingestion',purpose:'Efficient visual mesh, hierarchy, PBR material, skin and animation interchange.',carries:'Render geometry; normals/UVs; PBR textures; hierarchy; animation and optional metadata/extensions.',missing:'No reliable robot articulation, collision, mass/inertia, friction, actuator, sensor or task contract by default.',owner:'Classify as visual source; derive and validate collision/physics separately before awarding simulation-ready status.',url:'https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html'},
  {name:'Mesh / point-cloud bundle',role:'Runtime asset',files:'.obj · .stl · .ply · textures',home:'Reconstruction output · cross-tool geometry',purpose:'Lowest-common-denominator geometry for visual assets, collision generation or reconstruction QA.',carries:'Surface triangles or points; sometimes normals, vertex color, UVs and material references.',missing:'Often ambiguous units/up-axis; no hierarchy, articulation, collision intent, dynamics, task state or provenance unless sidecar metadata supplies them.',owner:'Require unit/up-axis manifest, watertightness report, visual/collision role, decimation history and source license.',url:'https://www.loc.gov/preservation/digital/formats/fdd/fdd000507.shtml'},
  {name:'MCAP / rosbag2',role:'Training data',files:'.mcap · rosbag metadata',home:'Raw robot and simulator telemetry',purpose:'Schema-aware, timestamped multi-channel source of truth for replay, debugging and forensic lineage.',carries:'Messages/channels/schemas; publish and log time; metadata; attachments; indices; compression and message-gap signals.',missing:'Not directly a policy-training API; episode boundaries, task IDs, action normalization, success and train/eval splits need derived products.',owner:'Preserve raw immutable logs; attach calibration/config/model hashes and convert through tested, versioned jobs.',url:'https://mcap.dev/spec'},
  {name:'LeRobotDataset v3',role:'Training data',files:'Parquet + MP4 + JSON/Parquet metadata',home:'PyTorch / Hugging Face robot learning',purpose:'Streaming and sharded multimodal robot episodes with a stable training-facing API.',carries:'Low-dimensional state/action/timestamps; per-camera video; schema/dtypes; FPS; tasks; episode offsets; normalization statistics.',missing:'It is not a simulator world or forensic replacement for raw telemetry; collision/contact state and calibration exist only if the schema includes them.',owner:'Version feature meaning, frame/action convention and source-log lineage; validate video-frame alignment and call finalize before release.',url:'https://huggingface.co/docs/lerobot/lerobot-dataset-v3'},
  {name:'RLDS / TFDS episodes',role:'Training data',files:'TFDS shards · episode → step schema',home:'Open X-Embodiment-era TensorFlow pipelines',purpose:'Canonical episodic abstraction for sequential decision-making, offline RL and imitation learning.',carries:'Episode metadata; ordered steps; observation/action/reward/discount; first/last/terminal/truncated semantics.',missing:'The reference repository is archived; field names beyond core lifecycle markers are dataset-defined and robot schemas remain heterogeneous.',owner:'Treat it as a legacy interoperability layer: retain dataset builder/version and document every observation/action feature.',url:'https://github.com/google-research/rlds'},
  {name:'robomimic / ManiSkill episode bundle',role:'Training data',files:'HDF5 trajectories + JSON environment metadata',home:'Offline IL/RL · simulation demonstration replay',purpose:'Compact action/state trajectories tied to a known simulator environment and replay toolchain.',carries:'Actions; observations or environment states; rewards/dones; episode metadata; environment/control configuration; seeds where recorded.',missing:'Replay can diverge across engine/device/version; a successful stored trajectory is not guaranteed to replay successfully under changed contact numerics.',owner:'Record initial/full simulator state, control mode and source; quarantine failed replays instead of silently rewriting the episode.',url:'https://maniskill.readthedocs.io/en/latest/user_guide/datasets/replay.html'},
  {name:'BDDL task definition',role:'Benchmark contract',files:'.bddl + JSON sampling/scene metadata',home:'BEHAVIOR / OmniGibson',purpose:'Declarative initial and goal predicates for long-horizon household activities.',carries:'Object categories/scopes; initial conditions; goal conditions and logical task structure.',missing:'No robot policy API, scene asset, simulator binary, action space, reset distribution or scoring procedure by itself.',owner:'Bundle the exact BDDL version with scene/object assets, sampler output and success-predicate implementation.',url:'https://behavior.stanford.edu/behavior_components/task_sampling.html'},
  {name:'Gym-style environment package',role:'Benchmark contract',files:'Python package + assets + configs',home:'ManiSkill · robosuite · LIBERO · RLBench',purpose:'Executable reset/step/render contract that binds a task to a simulator, robot and observation/action space.',carries:'Environment ID; reset distribution; observations; actions; reward/success; time limits; assets and controller hooks.',missing:'API compatibility does not guarantee identical physics, assets, camera calibration, task subset or evaluation protocol.',owner:'Publish a lockfile/container, environment IDs, controller config and deterministic evaluation manifest.',url:'https://maniskill.readthedocs.io/en/latest/user_guide/concepts/environments.html'},
  {name:'Benchmark release manifest',role:'Benchmark contract',files:'YAML/JSON manifest + hashes + harness',home:'Any credible public leaderboard or internal gate',purpose:'The reproducibility envelope that makes scores comparable across teams and dates.',carries:'Asset/runtime hashes; task and split IDs; robot/sensors; observation/action contract; seeds/trials; timeouts; oracle; metrics; submission rules.',missing:'There is no universal file extension or standard; governance quality depends on maintainers and version discipline.',owner:'Make the result row point to an immutable manifest and per-trial outcomes—not only a model name and percentage.',url:'https://robocasa.ai/leaderboard.html'},
];

export default function Real2SimPage(){
  const [input,setInput] = useState<'All'|Input>('All');
  const [output,setOutput] = useState<'All'|Output>('All');
  const [active,setActive] = useState(methods[0]);
  const [formatRole,setFormatRole] = useState<'All'|FormatRole>('All');
  const [activeFormat,setActiveFormat] = useState(simFormats[0]);
  const visible = useMemo(()=>methods.filter(m=>(input==='All'||m.inputs.includes(input))&&(output==='All'||m.output===output)),[input,output]);
  const visibleFormats=useMemo(()=>simFormats.filter(f=>formatRole==='All'||f.role===formatRole),[formatRole]);
  return <main className="r2s-page">
    <header className="training-topbar"><Link className="brand" href="/"><span>EØ</span>EGØ INDEX</Link><nav><Link href="/robotics-2026">Guide</Link><Link href="/real2sim" aria-current="page">Real2Sim</Link><Link href="/model-architectures">Architectures</Link><Link href="/training-strategies">Training</Link><Link href="/#matrix">Topology</Link></nav><Link className="edition" href="/">Owner audit · 31 Aug 2026</Link></header>

    <section className="r2s-hero"><div><p className="eyebrow">REAL VIDEO → EXECUTABLE WORLD</p><h1>RECONSTRUCT.<br/><em>GROUND.</em><br/>SIMULATE.</h1><p>Real2Sim is not one conversion. It is a chain of uncertain estimates: camera motion, metric geometry, actors, articulation, contact, physical parameters and executable task state. This workbench shows where each method actually stops.</p></div><div className="r2s-orbit" aria-label="Real2Sim transfer loop"><span>HUMAN / ROBOT VIDEO</span><b>3D + 4D</b><i>PHYSICS</i><em>POLICY</em><strong>REAL</strong></div></section>

    <section className="r2s-contract"><header><span>OWNER RULE 01</span><h2>A RENDER IS NOT A SIMULATOR.</h2></header><div>{stageLabels.map((s,i)=><article key={s}><b>0{i+1}</b><span>{s}</span>{i<stageLabels.length-1&&<i>→</i>}</article>)}</div></section>

    <section className="r2s-explorer"><div className="section-heading"><div><p className="eyebrow">01 / METHOD REGISTRY</p><h2>WHERE DOES THE<br/>PIPELINE STOP?</h2></div><p className="section-note">The x/y map is an editorial ordinal based on disclosed automation and physics coverage—not a performance leaderboard.</p></div>
      <div className="r2s-filters"><div><b>INPUT</b>{(['All','Human exo','Human ego','Robot rollout','Site scan','RGB-D','Single image'] as const).map(v=><button key={v} className={input===v?'active':''} onClick={()=>setInput(v)}>{v}</button>)}</div><div><b>OUTPUT</b>{(['All','Manipulation','Humanoid','Environment','Evaluation'] as const).map(v=><button key={v} className={output===v?'active':''} onClick={()=>setOutput(v)}>{v}</button>)}</div></div>
      <div className="r2s-grid"><div className="r2s-list"><header><span>{visible.length} methods</span><span>primary sources</span></header>{visible.map(m=><button key={m.name} className={active.name===m.name?'active':''} onClick={()=>setActive(m)}><span>{m.year}</span><strong>{m.name}</strong><small>{m.inputs.join(' + ')} → {m.output}</small><i>{m.access}</i></button>)}</div>
        <div className="r2s-map"><span className="r2s-axis top">PHYSICS / CONTACT COMPLETE</span><span className="r2s-axis bottom">VISUAL / KINEMATIC ONLY</span><span className="r2s-axis left">MANUAL</span><span className="r2s-axis right">AUTOMATED</span>{visible.map(m=><button key={m.name} aria-label={m.name} onClick={()=>setActive(m)} className={active.name===m.name?'active':''} style={{left:`${8+(m.automation-1)*21}%`,bottom:`${8+(m.physics-1)*20}%`}}><span>{m.name}</span></button>)}</div>
      </div>
      <article className="r2s-inspector"><header><div><p>{active.org} · {active.year} · {active.access}</p><h2>{active.name}</h2></div><a href={active.url} target="_blank" rel="noreferrer">Primary source ↗</a></header><div className="r2s-stage-strip">{stageLabels.map((s,i)=><div key={s} className={active.stages.includes(i+1)?'on':''}><b>0{i+1}</b><span>{s}</span></div>)}</div><div className="r2s-detail"><article><span>INPUT CONTRACT</span><p>{active.capture}</p></article><article><span>RECOVERS</span><div>{active.recover.map(x=><i key={x}>{x}</i>)}</div></article><article><span>WORLD REPRESENTATION</span><p>{active.representation}</p></article><article><span>SIM / LEARNING</span><p>{active.sim}</p></article><article><span>ROBOT BRIDGE</span><p>{active.transfer}</p></article><article className="metric"><span>NATIVE EVIDENCE</span><p>{active.metric}</p></article></div><footer><b>LIMIT</b><span>{active.limit}</span></footer></article>
    </section>

    <section className="r2s-native"><div className="section-heading"><div><p className="eyebrow">02 / NATIVE EVIDENCE</p><h2>WATCH THE ACTUAL<br/>TRANSFORMATION.</h2></div><p className="section-note">Media is served by the publishers. Nothing here is a generated stand-in.</p></div><div>{nativeMedia.map(item=><a href={item.url} target="_blank" rel="noreferrer" key={item.name}><video src={item.src} muted loop autoPlay playsInline preload="metadata"/><span><b>{item.name}</b><i>{item.label}</i><em>official demo ↗</em></span></a>)}</div></section>

    <section className="r2s-substrates"><div className="section-heading"><div><p className="eyebrow">03 / RECONSTRUCTION SUBSTRATES</p><h2>BEFORE THE TWIN,<br/>THE GROUND TRUTH.</h2></div><p className="section-note">These datasets and toolchains validate capture, tracking and geometry. They should not inherit a “physics simulator” badge.</p></div><div>{reconstructionSubstrates.map(s=><a key={s.name} href={s.url} target="_blank" rel="noreferrer"><span>{s.scale}</span><h3>{s.name}</h3><p>{s.signals}</p><footer>{s.role} ↗</footer></a>)}</div></section>

    <section className="r2s-production"><div className="section-heading"><div><p className="eyebrow">04 / PRODUCTION PIPELINES</p><h2>WHAT IS ACTUALLY<br/>SHIPPING.</h2></div><p className="section-note">Named deployments, productized reconstruction and early commercial claims are separated in the final column.</p></div><div className="r2s-prod-head"><span>Provider</span><span>Capture</span><span>Twin</span><span>Simulation bridge</span><span>Evidence</span><span>Owner caveat</span></div>{productionPipelines.map(row=><a href={row[6]} target="_blank" rel="noreferrer" className="r2s-prod-row" key={row[0]}>{row.slice(0,6).map((cell,i)=><span key={i}>{i===0?<b>{cell}</b>:cell}</span>)}</a>)}</section>

    <section className="r2s-formats" id="asset-formats"><div className="section-heading"><div><p className="eyebrow">05 / SIMULATION-READY ASSETS</p><h2>FILES ARE NOT<br/>A CONTRACT.</h2></div><p className="section-note">A visual export, an executable physics asset, a training episode and a reproducible benchmark are four different products.</p></div>
      <div className="r2s-readiness">{[
        ['01','VISUAL SOURCE','Mesh, hierarchy, UVs and textures. Useful for rendering and perception variation; not yet safe for contact.'],
        ['02','PHYSICS ASSET','Metric frames, collision, articulation, mass/inertia, materials, drives and validated contact behavior.'],
        ['03','TRAINING EPISODE','Synchronized observations, actions, states, task/outcome labels, calibration and immutable source lineage.'],
        ['04','BENCHMARK RELEASE','Locked assets/runtime, reset distribution, splits, oracle, trials, seeds, scoring and per-run results.'],
      ].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div>

      <article className="r2s-contact-verdict"><header><span>OWNER VERDICT · CONTACT-RICH EGO VIDEO · SEP 2026</span><b>NO UNIVERSAL WINNER</b></header><div><section><small>BEST END-TO-END</small><h3>EgoEngine</h3><p>Strongest disclosed path from egocentric video to paired robot observations, executable dexterous trajectories and zero-real-demo policy learning. Best when Aria depth/hand priors, a calibrated scene and known assets are available.</p><a href="https://egoengine.github.io/" target="_blank" rel="noreferrer">Primary evidence ↗</a></section><section><small>BEST DEFORMABLE PHYSICS</small><h3>EgoPhys</h3><p>Most direct ego-RGB evidence for identifying a deformable spring-mass twin and using it for real XArm6 planning—but only 19 short sequences, no tactile force, and not a general dexterous policy-data engine.</p><a href="https://hjhyunjinkim.github.io/EgoPhys/" target="_blank" rel="noreferrer">Primary evidence ↗</a></section><aside><small>THE SYSTEM STILL MISSING</small><p>EgoEngine-scale executable data <b>+</b> EgoPhys-style dynamics <b>+</b> tactile/force truth <b>+</b> active robot probing <b>+</b> broad held-out tasks.</p><strong>For rigid dexterous contact from a single non-ego human video, Video2Sim2Real is the strongest adjacent full-stack candidate—but remains under review.</strong></aside></div></article>

      <div className="r2s-sim-grade"><header><div><span>DEFORMABLE TWIN LADDER</span><h3>WHAT “SIMULATION-GRADE” ADDS.</h3></div><p>Simulation-grade is not prettier replay. It means executable counterfactual dynamics, stable stepping, controllable contact, validation under unseen interactions and enough throughput for planning or learning.</p></header><div className="r2s-sim-head"><span>System</span><span>Capture / model</span><span>Executable use</span><span>Grade earned</span><span>Why it is not EgoPhys-at-scale</span></div>{[
        ['EgoPhys','Single Aria ego RGB · learned spring–mass stiffness prior','MPPI planning on real XArm6','EGO-GENERALIZATION','19 short sequences; no tactile force; one object at a time.','https://hjhyunjinkim.github.io/EgoPhys/'],
        ['PhysTwin','Sparse controlled videos · object-specific spring–mass + Gaussians','Real-time interaction, teleoperation and model-based planning','INTERACTIVE SIM','Capture/optimization is heavier and not an ego-data engine.','https://jianghanxiao.github.io/phystwin-web/'],
        ['EMPM','Multi-view RGB-D · differentiable Material Point Method','Online parameter updates and controller rollouts for continuum materials','PHYSICS DEPTH','Stronger sensors and control assumptions; code is not yet released.','https://embodied-mpm.github.io/'],
        ['Boba','A prebuilt PhysTwin asset · batched surrogate dynamics','Thousands of rendered sim frames/s; MPC and PPO','TRAINING THROUGHPUT','Accelerates an existing twin; does not improve its inverse identification.','https://jianxiapyh.github.io/Boba-project-page/'],
        ['Real2Sim-Eval','Scene scan + robot/human videos · 3DGS + PhysTwin','Policy evaluation with public task artifacts','EVALUATION GRADE','Only three task families and manual real/sim initial-state alignment.','https://real2sim-eval.github.io/'],
        ['SoftMimicGen','Authored high-fidelity deformable environments + seed demos','Scalable synthetic data across four embodiments','DATA GENERATION','Not real-to-sim reconstruction and does not consume ego video.','https://softmimicgen.github.io/'],
      ].map(row=><a href={row[5]} target="_blank" rel="noreferrer" key={row[0]}>{row.slice(0,5).map((cell,i)=><span key={i}>{i===0?<b>{cell}</b>:i===3?<i>{cell}</i>:cell}</span>)}</a>)}</div>

      <div className="r2s-format-controls"><b>FORMAT ROLE</b>{(['All','Runtime asset','Training data','Benchmark contract'] as const).map(role=><button key={role} className={formatRole===role?'active':''} onClick={()=>{setFormatRole(role);if(role!=='All'){const next=simFormats.find(f=>f.role===role);if(next)setActiveFormat(next)}}}>{role}</button>)}</div>
      <div className="r2s-format-workbench"><div className="r2s-format-list"><header><span>{visibleFormats.length} contracts</span><span>select to inspect</span></header>{visibleFormats.map(f=><button key={f.name} className={activeFormat.name===f.name?'active':''} onClick={()=>setActiveFormat(f)}><span>{f.role}</span><strong>{f.name}</strong><small>{f.files}</small></button>)}</div><article className="r2s-format-detail"><header><span>{activeFormat.role}</span><a href={activeFormat.url} target="_blank" rel="noreferrer">Specification / source ↗</a></header><h3>{activeFormat.name}</h3><p className="r2s-format-purpose">{activeFormat.purpose}</p><dl><dt>FILES</dt><dd>{activeFormat.files}</dd><dt>HOME RUNTIME</dt><dd>{activeFormat.home}</dd><dt>PORTABLE CONTENT</dt><dd>{activeFormat.carries}</dd><dt>DOES NOT GUARANTEE</dt><dd>{activeFormat.missing}</dd><dt>OWNER RULE</dt><dd>{activeFormat.owner}</dd></dl></article></div>

      <div className="r2s-generative"><header><div><span>ARTISTIC / GENERATIVE MESH COMPATIBILITY</span><h3>RENDER-READY ≠ ROBOTICS-READY</h3></div><p>Keep one validated collision/physics asset and swap artistic render variants around it. Style is a perception-domain variable, not evidence for mass, friction or contact.</p></header><div className="r2s-gen-table"><div className="head"><span>Generator</span><span>Native value</span><span>Useful robotics role</span><span>Conversion debt</span><span>Status</span></div><a href="https://docs.meshy.ai/en" target="_blank" rel="noreferrer"><span><b>Meshy</b><small>Text / image → 3D</small></span><span>GLB, FBX, OBJ, STL, USDZ, 3MF; remesh, animation and optional PBR maps.</span><span>Visual objects, digital cousins, texture/style and geometry variation for synthetic perception data.</span><span>Verify metric scale and topology; create collision proxy; segment parts; add joints, inertials, contact materials and provenance.</span><span><i>VISUAL SOURCE</i>compatible after physics authoring</span></a><a href="https://github.com/VAST-AI-Research/TripoSG" target="_blank" rel="noreferrer"><span><b>VAST / Tripo</b><small>TripoSG · TripoSR · Studio</small></span><span>High-fidelity or controlled-face GLB meshes; Studio advertises GLB, FBX, OBJ and USD plus segmentation, rigging and PBR.</span><span>Fast shape candidates, stylized/photoreal cousins, object libraries and render-domain randomization.</span><span>Game/animation rigging is not robot articulation. Validate dimensions, interfaces, watertightness, collision, dynamics and manipulation affordances.</span><span><i>VISUAL SOURCE</i>compatible after physics authoring</span></a><div className="anchor"><span><b>Scan / CAD anchor</b><small>Measured or engineered source</small></span><span>Metric geometry, component structure and sometimes material or mass documentation.</span><span>Canonical shape/scale and interface anchor; generated meshes become bounded visual cousins.</span><span>Still needs simulation collision, dynamics, controller and task validation.</span><span><i>PREFERRED ANCHOR</i>for contact benchmarks</span></div></div>
        <div className="r2s-mesh-flow">{['PROMPT / IMAGE','ART MESH','GEOMETRY QC','SCALE + PARTS','COLLISION','JOINTS + DYNAMICS','USD / MJCF / URDF','TRAIN + BENCHMARK'].map((x,i)=><span key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}{i<7&&<i>→</i>}</span>)}</div>
        <div className="r2s-mesh-checks">{[
          ['GEOMETRY','Scale, up-axis, normals, manifoldness, thickness, decimation and LOD.'],
          ['APPEARANCE','PBR maps, color space, UV integrity, material IDs and style-distribution labels.'],
          ['INTERACTION','Convex/decomposed collision, part semantics, joint axes/limits, grasp and support surfaces.'],
          ['DYNAMICS','Mass, center of mass, inertia, friction, restitution, damping and compliance.'],
          ['PROVENANCE','Prompt/input, generator/model version, seed, source license, export hash and every repair.'],
          ['EVALUATION','Lock visual variants by split; disclose stylization; prevent test-asset and source-image leakage.'],
        ].map(x=><article key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div>
      </div>
    </section>

    <section className="r2s-metrics"><div className="section-heading"><div><p className="eyebrow">06 / EVIDENCE LEDGER</p><h2>DO NOT COLLAPSE<br/>THE METRICS.</h2></div><p className="section-note">Geometry, rendering, pose, dynamics and task success answer different questions. Native units stay native.</p></div><div className="r2s-metric-head"><span>Method</span><span>Geometry / rendering</span><span>Motion / physics</span><span>Downstream</span><span>Interpretation</span></div>{[
      ['ROSE','Scene Chamfer 0.6776 avg · object Chamfer 0.01782 avg','Translation APE 0.01418 · rotation RPE 4.866°','0.90 simulated two-stage RL · 11/13 real trials','Broad end-to-end evidence; small real trial count.'],
      ['Human2Sim2Robot','Uses reconstructed object and hand state','Object-centric reward + RL contact adaptation','+55% vs open-loop replay · +68% vs augmented IL','Policy delta, not a reconstruction score.'],
      ['RialTo','User-edited scanned digital twins','Domain randomization in the twin','>67% robustness increase reported','Relative robustness across its task suite.'],
      ['Digital Cousins','Semantic/geometric asset similarity','Affordance-equivalent, not exact dynamics','90% vs 25% zero-shot success reported','Evidence that diversity can beat exactness.'],
      ['VideoMimic','Metric 4D human + dense aligned scene','Physics tracking + mass/friction/latency randomization','Real G1 contextual control','Locomotion/whole-body evidence, not hand dexterity.'],
      ['Real2Sim-Eval','3DGS color/pose alignment','Soft-body physical parameter fitting','Sim/real policy correlation reported','Evaluation fidelity, not policy-training scale.'],
    ].map(r=><div className="r2s-metric-row" key={r[0]}>{r.map((v,i)=><span key={i}>{i===0?<b>{v}</b>:v}</span>)}</div>)}</section>

    <section className="r2s-gaps"><div><p className="eyebrow">07 / LIMITATIONS</p><h2>THE SIX GAPS<br/>A DEMO HIDES.</h2></div><div>{gaps.map((g,i)=><article key={g[0]}><b>0{i+1}</b><h3>{g[0]}</h3><p>{g[1]}</p></article>)}</div></section>

    <section className="r2s-future"><div className="section-heading"><div><p className="eyebrow">08 / WHAT LOOKS PROMISING</p><h2>FROM STATIC TWIN<br/>TO TESTABLE WORLD.</h2></div></div><div>{[
      ['ACTIVE IDENTIFICATION','Let the robot push, lift, shake and probe. Short active experiments collapse mass, friction, compliance and joint uncertainty better than passive video.'],
      ['RELATIONAL 4D','Represent object state, support, containment, articulation and contact events—not only pixels or independent trajectories.'],
      ['TWIN + COUSIN DISTRIBUTIONS','Use the measured twin as the anchor and generate bounded cousins around uncertainty. Train on the posterior, not one brittle scene.'],
      ['DIFFERENTIABLE VALIDATION','Optimize physics against held-out rollouts, then report residuals in image, pose, force and task-outcome space.'],
      ['FAILURE-CLOSED AGENTS','Agentic assembly needs typed schemas, unit checks, collision tests, provenance and automatic rejection—not only a VLM saying the scene looks right.'],
      ['MEMORY-BEARING SIMS','Long-horizon evaluation needs persistent object state, irreversible actions, hidden state and revisits; episodic resets erase the agency problem.'],
    ].map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,'0')}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>

    <section className="r2s-owner"><div><p className="eyebrow">09 / DEPLOYMENT GATE</p><h2>WHAT A DATA OWNER<br/>SHOULD REQUIRE.</h2></div><ol><li><b>Calibration manifest</b><span>Intrinsics, extrinsics, clock domains, scale source, gravity residual and coordinate conventions.</span></li><li><b>Asset contract</b><span>Visual mesh, watertight collision mesh, joints/limits, mass/inertia, friction, compliance and provenance.</span></li><li><b>Trajectory contract</b><span>Human/robot/object frames, confidence, contact intervals, action convention and resampling history.</span></li><li><b>Validation pack</b><span>Held-out real rollouts with pixel, pose, force/contact and outcome residuals—plus failure cases.</span></li><li><b>Uncertainty budget</b><span>Every inferred quantity has bounds; simulation randomization stays within measured or justified ranges.</span></li><li><b>Reproducible export</b><span>Versioned USD/MJCF/URDF assets, simulator version, seed, controller and policy checkpoint.</span></li></ol></section>
  </main>;
}
