'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';

type Access = 'Open weights' | 'Partial release' | 'Closed';
type Disclosure = 'HIGH' | 'MEDIUM' | 'LOW';
type Record = {
  model:string; org:string; access:Access; disclosure:Disclosure; url:string;
  preScale:string; preData:string[]; preObjective:string; preStrategy:string;
  postScale:string; postData:string[]; postObjective:string; postStrategy:string;
  loop:string; warning:string;
};

const records: Record[] = [
  {model:'OpenVLA 7B',org:'Stanford · Berkeley · TRI',access:'Open weights',disclosure:'HIGH',url:'https://openvla.github.io/',preScale:'970K robot episodes',preData:['Open X-Embodiment','Magic Soup++','RGB + language + actions'],preObjective:'Next action-token prediction on a curated cross-embodiment mixture.',preStrategy:'Prismatic VLM initialization followed by robot-action pre-training.',postScale:'Task-specific · not one canonical count',postData:['Target robot demonstrations','Optional LoRA / full fine-tune'],postObjective:'Adapt the shared action vocabulary to a target robot and camera domain.',postStrategy:'Supervised behavior cloning; no published online self-improvement loop.',loop:'Offline demonstrations → checkpoint → target fine-tune.',warning:'Open weights and mixture configs; raw source rights remain dataset-specific.'},
  {model:'OpenVLA-OFT',org:'Stanford',access:'Open weights',disclosure:'HIGH',url:'https://github.com/moojink/openvla-oft',preScale:'Inherits OpenVLA · 970K episodes',preData:['OpenVLA checkpoint','OXE inherited'],preObjective:'Reuse the general visual-language-action representation.',preStrategy:'Checkpoint inheritance; pre-training is not repeated by most users.',postScale:'20 / 30 / 45 / 300 ALOHA demos by task',postData:['ALOHA demonstrations','LIBERO suites','Proprioception + multi-view RGB'],postObjective:'Produce continuous parallel action chunks at higher control rates.',postStrategy:'Supervised optimized fine-tuning with action chunking and continuous heads.',loop:'Base checkpoint → target demonstrations → deployment checkpoint.',warning:'The published ALOHA counts are task recipes, not a universal post-training budget.'},
  {model:'Octo 27M / 93M',org:'Berkeley · Stanford',access:'Open weights',disclosure:'HIGH',url:'https://octo-models.github.io/',preScale:'800K episodes · 25 OXE datasets',preData:['Open X-Embodiment','Image history','Language or goal images'],preObjective:'Learn a flexible diffusion action prior across observation and action spaces.',preStrategy:'Cross-embodiment masked transformer plus diffusion readout.',postScale:'Often 50–100 target demos',postData:['Target embodiment demonstrations','New observation/action heads'],postObjective:'Specialize a general representation to an unseen embodiment or task.',postStrategy:'Supervised fine-tuning; adapters can isolate new input/output interfaces.',loop:'Open mixture → generalist → small target set.',warning:'Evaluation spans multiple robots, but no autonomous data flywheel is claimed.'},
  {model:'π0.5',org:'Physical Intelligence',access:'Open weights',disclosure:'MEDIUM',url:'https://www.pi.website/blog/pi05',preScale:'10K+ robot hours in released OpenPI family',preData:['Cross-embodiment robot data','~400 h mobile household data','Web/VQA/semantic co-training'],preObjective:'Learn broad physical semantics and continuous action generation.',preStrategy:'VLM co-training plus flow-matching action expert across robot families.',postScale:'Undisclosed per deployment',postData:['Target demonstrations','Verbal instructions','Subtask labels / coaching'],postObjective:'Convert broad competence into reliable household behaviors in a target embodiment.',postStrategy:'Supervised post-training with high-level semantic supervision; autonomous experience is described as future work.',loop:'Private foundation mixture → semantic post-training → expert checkpoints.',warning:'Weights/code are public; the complete physical-data manifest and post-training counts are not.'},
  {model:'GR00T N1.7',org:'NVIDIA',access:'Open weights',disclosure:'MEDIUM',url:'https://github.com/NVIDIA/Isaac-GR00T',preScale:'~32K h real+ego · ~8K h simulation',preData:['Real robot demonstrations','EgoScale human ego','BEHAVIOR / RoboCasa / GR-1 sim'],preObjective:'Learn cross-embodiment visual-language-action priors for humanoids.',preStrategy:'Heterogeneous real, human and simulated co-training with embodiment conditioning.',postScale:'Source-dependent · not globally itemized',postData:['Target robot demonstrations','Synthetic trajectories','Isaac simulation'],postObjective:'Adapt the foundation policy to a robot, task suite and action interface.',postStrategy:'Supervised fine-tuning plus simulation-assisted data generation and evaluation.',loop:'Real + ego + sim foundation → embodiment adaptation → deployment.',warning:'The headline 32K-hour figure combines real robot and human ego; do not treat it as 32K robot hours.'},
  {model:'SmolVLA 450M',org:'Hugging Face',access:'Open weights',disclosure:'HIGH',url:'https://github.com/huggingface/lerobot',preScale:'46.9 h · 11.1K episodes',preData:['LeRobot Community v1','128 datasets','Mostly SO-100 manipulation'],preObjective:'Build a compact, reproducible VLA prior usable on consumer hardware.',preStrategy:'Community robot behavior cloning with a small language-conditioned action model.',postScale:'Commonly ~50 demonstrations',postData:['Target LeRobot episodes','Task instruction','Robot state'],postObjective:'Fit one deployment/task without retraining a giant foundation model.',postStrategy:'Supervised target-task fine-tuning through the public LeRobot stack.',loop:'Public corpus → small base → local demonstrations.',warning:'The clearest audit trail in the group, but capability breadth is intentionally modest.'},
  {model:'RDT-1B',org:'Tsinghua',access:'Open weights',disclosure:'HIGH',url:'https://github.com/thu-ml/RoboticsDiffusionTransformer',preScale:'1M+ episodes · 46 datasets',preData:['Multi-robot demonstrations','Image + language + proprioception','Unified 128-D interface'],preObjective:'Model heterogeneous robot action trajectories with a diffusion transformer.',preStrategy:'Cross-embodiment supervised pre-training after action/state unification.',postScale:'6K+ ALOHA episodes',postData:['Bimanual ALOHA demonstrations','Target-platform observations'],postObjective:'Transfer the shared representation into high-rate bimanual control.',postStrategy:'Supervised target-embodiment fine-tuning; no reported online RL loop.',loop:'46-dataset pre-training → 6K+ bimanual adaptation episodes.',warning:'One million episodes and six thousand ALOHA episodes are different stages, not additive benchmark evidence.'},
  {model:'CogACT',org:'Microsoft Research Asia',access:'Open weights',disclosure:'HIGH',url:'https://cogact.github.io/',preScale:'0.4M OXE trajectories',preData:['Open X-Embodiment','RGB + language','Prismatic backbone'],preObjective:'Learn general visual-language features with a continuous action diffusion module.',preStrategy:'VLM initialization plus cross-robot action pre-training.',postScale:'391 Realman demonstrations disclosed',postData:['Realman target data','Separate Franka adaptation'],postObjective:'Ground the cross-robot prior in a specific controller and workspace.',postStrategy:'Supervised embodiment fine-tuning.',loop:'OXE prior → target robot demos → specialist checkpoint.',warning:'Franka adaptation volume and downstream raw-data release remain incomplete.'},
  {model:'LingBot-VLA 2.0',org:'Robbyant · Ant Group',access:'Open weights',disclosure:'MEDIUM',url:'https://github.com/Robbyant/lingbot-vla-v2',preScale:'50K h robot + 10K h human ego',preData:['20 robot configurations','Captured ego manipulation','RGB/depth + canonical 55-D actions'],preObjective:'Learn a single cross-embodiment action representation from robot and human behavior.',preStrategy:'Large mixed physical pre-training with an MoE flow action expert.',postScale:'Varies by platform · undisclosed globally',postData:['RoboTwin 2.0','Real robot target sets','Platform-specific configuration'],postObjective:'Specialize the generalist to long-horizon and mobile manipulation setups.',postStrategy:'Supervised post-training; no autonomous fleet-learning volume is reported.',loop:'Large private corpus → platform post-training → public weights.',warning:'Hours and configuration counts are author-reported; source-level manifests are not released.'},
  {model:'MolmoAct2 5B',org:'Ai2',access:'Open weights',disclosure:'HIGH',url:'https://github.com/allenai/molmoact2',preScale:'720+ h YAM + named robot mixtures',preData:['Bimanual YAM','DROID / Bridge / Fractal','SO-100/101','3M embodied-reasoning examples'],preObjective:'Join visual-spatial reasoning, depth-aware tokens and physical action generation.',preStrategy:'Embodied-reasoning VLM co-training plus flow-matching action pre-training.',postScale:'Checkpoint-specific',postData:['DROID','SO-100/101','Bimanual YAM','LIBERO'],postObjective:'Produce deployable experts for a named embodiment or benchmark.',postStrategy:'Supervised fine-tuning with openly released recipes, datasets and rollouts.',loop:'Reasoning + robot foundation → named target mixture → deployable expert.',warning:'Evaluation rollouts are published artifacts, not evidence of autonomous training data.'},
  {model:'τ0-VLA',org:'Shanghai Innovation Institute',access:'Open weights',disclosure:'MEDIUM',url:'https://tau0-vla.github.io/',preScale:'40,115 h real robot experience',preData:['Fixed-base robots','Bimanual robots','Mobile platforms','Multimodal co-training'],preObjective:'Build a broad 40-D cross-embodiment action prior.',preStrategy:'Large-scale heterogeneous robot pre-training; exact sources and weights are private.',postScale:'Separate fine-tune per deployment',postData:['Target robot demonstrations','Subtask memory traces','World-model candidates'],postObjective:'Sustain long workflows through memory and test-time action selection.',postStrategy:'Supervised deployment adaptation plus test-time world-model search; search is inference, not new training data.',loop:'Large private corpus → deployment fine-tune → memory/search at inference.',warning:'40,115 hours are disclosed only as an aggregate; exact parameter count and source manifest remain absent.'},
  {model:'WALL-OSS-0.5',org:'X Square Robot',access:'Open weights',disclosure:'MEDIUM',url:'https://github.com/X-Square-Robot/wall-x',preScale:'1M+ trajectories sampled per epoch',preData:['20+ embodiments','Self-collected + open robot data','90M grounded multimodal samples'],preObjective:'Learn grounded semantics and reusable robot actions across embodiments.',preStrategy:'Robot trajectory pre-training plus a large vision-language grounding stream.',postScale:'12M synthetic bridge samples + target data',postData:['Embodied bridge QA','Target demonstrations','Flow or FAST action branches'],postObjective:'Align visual-language reasoning with action and specialize deployment heads.',postStrategy:'Synthetic embodied instruction generation plus supervised adaptation.',loop:'Grounding corpus + robot mixture → bridge supervision → target policy.',warning:'Per-epoch sample count is not a unique trajectory count; raw proprietary mixture is undisclosed.'},
  {model:'JoyAI-RA 0.5',org:'JD JoyAI',access:'Partial release',disclosure:'MEDIUM',url:'https://joyai-ra-05.github.io/',preScale:'53K+ h ego · 11K+ h sim · 8K+ h robot',preData:['EgoLive human tasks','Real robot demonstrations','Simulation','Web data'],preObjective:'Unify human, robot and simulated experience in a cross-embodiment world-action model.',preStrategy:'Multi-source physical pre-training with latent/action alignment.',postScale:'Autonomous interaction volume undisclosed',postData:['Inner-loop residual RL','Successful interactions','Outer-loop aggregation'],postObjective:'Improve task success after supervised pre-training and feed successes back into the system.',postStrategy:'Residual reinforcement learning plus iterative successful-trajectory aggregation.',loop:'Multi-source pre-training → residual RL → collect successes → update.',warning:'Weights and complete training code are not public; autonomous hours/rollouts are not quantified.'},
  {model:'Zero-WAM',org:'Robbyant Research',access:'Partial release',disclosure:'MEDIUM',url:'https://github.com/robbyant-research/Zero-WAM',preScale:'~400K robot trajectories sampled per epoch',preData:['AgiBot World','InternData-A1','OXE','RoboCOIN / RoboMIND'],preObjective:'Initialize a world-action model from broad robot trajectories and a video generator.',preStrategy:'Wan-2.2 video-model initialization plus task-balanced robot-action training.',postScale:'74.2K HumanGen pairs · 2,150 RoboTwin + 252 real ICL pairs',postData:['Synthetic ego + third-person HumanGen','RoboTwin','Small real-world target sets'],postObjective:'Teach in-context task following and target-domain manipulation from generated demonstrations.',postStrategy:'Synthetic human–robot ICL bridge plus supervised simulator/real adaptation.',loop:'Robot trajectories → generated human-like videos → ICL post-training.',warning:'HumanGen is synthetic video generated from robot trajectories—not captured human ego data; release was announced, so availability must be rechecked.'},
];

const accessOptions: ('All'|Access)[] = ['All','Open weights','Partial release','Closed'];

export default function TrainingStrategiesPage() {
  const [access,setAccess] = useState<'All'|Access>('All');
  const [query,setQuery] = useState('');
  const [active,setActive] = useState(records[3]);
  const visible = useMemo(()=>records.filter(record => (access==='All'||record.access===access) && (!query || [record.model,record.org,...record.preData,...record.postData,record.preStrategy,record.postStrategy].join(' ').toLowerCase().includes(query.toLowerCase()))),[access,query]);
  return <main className="training-page">
    <header className="training-topbar"><Link className="brand" href="/"><span>EØ</span>EGØ INDEX</Link><nav><Link href="/robotics-2026">Guide</Link><Link href="/real2sim">Real2Sim</Link><Link href="/model-architectures">Architectures</Link><Link href="/training-strategies" aria-current="page">Training</Link><Link href="/#matrix">Topology</Link></nav><Link className="edition" href="/"><i/>Owner audit · 31 Aug 2026</Link></header>

    <section className="training-hero">
      <p className="eyebrow">MODEL DATA LEDGER / PRE-TRAINING ≠ POST-TRAINING</p>
      <h1>FOUNDATION<br/><em>THEN FIT.</em></h1>
      <p>Pre-training buys breadth. Post-training buys embodiment fit, task reliability, and sometimes an improvement loop. This page keeps their data, objectives, and evidence separate.</p>
      <div className="training-hero-stats"><span><b>{records.length}</b> model families</span><span><b>{records.filter(r=>r.access==='Open weights').length}</b> open-weight stacks</span><span><b>{records.filter(r=>r.loop.toLowerCase().includes('rl')).length}</b> explicit RL loops</span><span><b>{records.filter(r=>r.disclosure==='HIGH').length}</b> high-disclosure records</span></div>
    </section>

    <section className="training-primer">
      <article><span>01 / PRE-TRAINING</span><h2>BREADTH PRIOR</h2><p>Large heterogeneous mixtures teach perception, language grounding, cross-embodiment regularities, and a broad action prior.</p><div><b>Typical data</b><i>robot demonstrations</i><i>human ego</i><i>simulation</i><i>web / VQA</i></div></article>
      <div className="training-arrow"><b>CHECKPOINT</b><i>→</i><small>representation + action prior</small></div>
      <article><span>02 / POST-TRAINING</span><h2>DEPLOYMENT FIT</h2><p>Smaller targeted datasets align the foundation model to a robot, controller, scene distribution, and operational objective.</p><div><b>Typical strategies</b><i>supervised fine-tuning</i><i>action-head adaptation</i><i>RL / preference</i><i>test-time search</i></div></article>
    </section>

    <section className="training-units">
      <header><span>Owner rule 01</span><h2>DO NOT ADD INCOMPATIBLE UNITS.</h2></header>
      <div>{[['HOURS','clock-time exposure'],['EPISODES','bounded sequences'],['TRAJECTORIES','action-state paths'],['SAMPLES / EPOCH','sampling rate, not corpus size'],['SYNTHETIC PAIRS','generated supervision'],['ROLLOUTS','policy interactions; training only if fed back']].map(item=><article key={item[0]}><b>{item[0]}</b><p>{item[1]}</p></article>)}</div>
    </section>

    <section className="training-ledger">
      <div className="section-heading"><div><p className="eyebrow">03 / MODEL-BY-MODEL LEDGER</p><h2>WHAT HAPPENS<br/>BEFORE AND AFTER.</h2></div><p className="section-note">Counts remain in publisher-native units. “Undisclosed” is a data point, not an invitation to estimate.</p></div>
      <div className="training-filters"><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search model, dataset, strategy…"/></label><div>{accessOptions.map(item=><button key={item} className={access===item?'active':''} onClick={()=>setAccess(item)}>{item}</button>)}</div></div>
      <div className="training-ledger-head"><span>Model</span><span>Pre-training data + objective</span><span>Post-training data + strategy</span><span>Loop / disclosure</span></div>
      {visible.map(record=><button className={'training-record '+(active.model===record.model?'active':'')} key={record.model} onClick={()=>setActive(record)}>
        <span><strong>{record.model}</strong><small>{record.org}</small><i>{record.access}</i></span>
        <span><b>{record.preScale}</b><p>{record.preData.join(' · ')}</p><em>{record.preObjective}</em></span>
        <span><b>{record.postScale}</b><p>{record.postData.join(' · ')}</p><em>{record.postStrategy}</em></span>
        <span><b>{record.disclosure} DISCLOSURE</b><p>{record.loop}</p><small>{record.warning}</small></span>
      </button>)}
      {!visible.length && <div className="training-empty">No model matches this slice.</div>}
    </section>

    <section className="training-inspector">
      <header><div><p>SELECTED PIPELINE / {active.access}</p><h2>{active.model}</h2></div><a href={active.url} target="_blank" rel="noreferrer">Primary source ↗</a></header>
      <div className="strategy-flow">
        <article><span>RAW SOURCES</span>{active.preData.map(item=><i key={item}>{item}</i>)}</article><b>→</b>
        <article><span>PRE-TRAIN</span><h3>{active.preStrategy}</h3><p>{active.preObjective}</p></article><b>→</b>
        <article><span>POST DATA</span>{active.postData.map(item=><i key={item}>{item}</i>)}</article><b>→</b>
        <article><span>POST-TRAIN / INFERENCE</span><h3>{active.postStrategy}</h3><p>{active.loop}</p></article>
      </div>
      <footer><b>{active.disclosure} DISCLOSURE</b><span>{active.warning}</span></footer>
    </section>

    <section className="training-rules">
      <div><p className="eyebrow">04 / ACCOUNTING RULES</p><h2>A RIGOROUS<br/>TRAINING LEDGER.</h2></div>
      <ol><li><b>Separate stage.</b><span>Foundation pre-training, embodiment adaptation, task fine-tuning, RL, and inference-time search are different operations.</span></li><li><b>Separate origin.</b><span>Captured human ego, synthetic human-like video, teleoperated robot trajectories, autonomous rollouts, and simulation retain distinct provenance.</span></li><li><b>Separate availability.</b><span>A public checkpoint does not imply that its training corpus is public. A demo video does not imply a downloadable rollout.</span></li><li><b>Separate evaluation.</b><span>Evaluation rollouts count as training data only when the publisher explicitly feeds them into an update loop.</span></li></ol>
    </section>
  </main>;
}
